package crypto

import (
	"errors"
	"math"
)

var ErrInvalidRandomBound = errors.New("invalid random bound")

// FillRandomBytes fills the provided slice using the Go-native CSPRNG.
func FillRandomBytes(dst []byte) error {
	for offset := 0; offset < len(dst); {
		block, err := GenerateKey()
		if err != nil {
			return err
		}
		offset += copy(dst[offset:], block)
	}
	return nil
}

// RandomBytes returns a random byte slice generated by the Go-native CSPRNG.
func RandomBytes(length int) ([]byte, error) {
	if length < 0 {
		return nil, ErrInvalidRandomBound
	}
	out := make([]byte, length)
	if err := FillRandomBytes(out); err != nil {
		return nil, err
	}
	return out, nil
}

// RandomIntN returns an integer in [0, n) using rejection sampling.
func RandomIntN(n int) (int, error) {
	if n <= 0 {
		return 0, ErrInvalidRandomBound
	}
	if n == 1 {
		return 0, nil
	}
	max := uint64(n)
	limit := math.MaxUint64 - (math.MaxUint64 % max)

	for {
		b, err := RandomBytes(8)
		if err != nil {
			return 0, err
		}
		r := uint64(b[0])<<56 |
			uint64(b[1])<<48 |
			uint64(b[2])<<40 |
			uint64(b[3])<<32 |
			uint64(b[4])<<24 |
			uint64(b[5])<<16 |
			uint64(b[6])<<8 |
			uint64(b[7])
		if r < limit {
			return int(r % max), nil
		}
	}
}
