// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: analytics/analytics.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryEventsRequest represents a request to query analytics events.
type QueryEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filters       []*Filter              `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"`
	SortField     string                 `protobuf:"bytes,4,opt,name=sort_field,json=sortField,proto3" json:"sort_field,omitempty"`
	SortOrder     SortOrder              `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3,enum=aegion.analytics.SortOrder" json:"sort_order,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	EventType     string                 `protobuf:"bytes,7,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEventsRequest) Reset() {
	*x = QueryEventsRequest{}
	mi := &file_analytics_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsRequest) ProtoMessage() {}

func (x *QueryEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsRequest.ProtoReflect.Descriptor instead.
func (*QueryEventsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *QueryEventsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QueryEventsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *QueryEventsRequest) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *QueryEventsRequest) GetSortField() string {
	if x != nil {
		return x.SortField
	}
	return ""
}

func (x *QueryEventsRequest) GetSortOrder() SortOrder {
	if x != nil {
		return x.SortOrder
	}
	return SortOrder_SORT_ORDER_UNSPECIFIED
}

func (x *QueryEventsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *QueryEventsRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

// QueryEventsResponse represents the response from querying events.
type QueryEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	NextPageToken string                 `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEventsResponse) Reset() {
	*x = QueryEventsResponse{}
	mi := &file_analytics_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventsResponse) ProtoMessage() {}

func (x *QueryEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventsResponse.ProtoReflect.Descriptor instead.
func (*QueryEventsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *QueryEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *QueryEventsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *QueryEventsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// GetDashboardRequest represents a request to get a dashboard.
type GetDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardRequest) Reset() {
	*x = GetDashboardRequest{}
	mi := &file_analytics_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardRequest) ProtoMessage() {}

func (x *GetDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *GetDashboardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DashboardData represents dashboard data with events and metrics.
type DashboardData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dashboard     *Dashboard             `protobuf:"bytes,1,opt,name=dashboard,proto3" json:"dashboard,omitempty"`
	Events        []*Event               `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	Metrics       []*Metric              `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardData) Reset() {
	*x = DashboardData{}
	mi := &file_analytics_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardData) ProtoMessage() {}

func (x *DashboardData) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardData.ProtoReflect.Descriptor instead.
func (*DashboardData) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *DashboardData) GetDashboard() *Dashboard {
	if x != nil {
		return x.Dashboard
	}
	return nil
}

func (x *DashboardData) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *DashboardData) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// ExecuteQueryRequest represents a request to execute a query.
type ExecuteQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Parameters    []string               `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryRequest) Reset() {
	*x = ExecuteQueryRequest{}
	mi := &file_analytics_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryRequest) ProtoMessage() {}

func (x *ExecuteQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryRequest.ProtoReflect.Descriptor instead.
func (*ExecuteQueryRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteQueryRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *ExecuteQueryRequest) GetParameters() []string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ExecuteQueryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ExecuteQueryRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// CreateDashboardRequest represents a request to create a dashboard.
type CreateDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Public        bool                   `protobuf:"varint,4,opt,name=public,proto3" json:"public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDashboardRequest) Reset() {
	*x = CreateDashboardRequest{}
	mi := &file_analytics_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDashboardRequest) ProtoMessage() {}

func (x *CreateDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDashboardRequest.ProtoReflect.Descriptor instead.
func (*CreateDashboardRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDashboardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDashboardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateDashboardRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateDashboardRequest) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

// UpdateDashboardRequest represents a request to update a dashboard.
type UpdateDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	Public        bool                   `protobuf:"varint,5,opt,name=public,proto3" json:"public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDashboardRequest) Reset() {
	*x = UpdateDashboardRequest{}
	mi := &file_analytics_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDashboardRequest) ProtoMessage() {}

func (x *UpdateDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDashboardRequest.ProtoReflect.Descriptor instead.
func (*UpdateDashboardRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDashboardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDashboardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDashboardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateDashboardRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpdateDashboardRequest) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

// StreamEventsRequest represents a request to stream events.
type StreamEventsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Filters           []*Filter              `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	Category          string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	EventType         string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	IncludeHistorical bool                   `protobuf:"varint,4,opt,name=include_historical,json=includeHistorical,proto3" json:"include_historical,omitempty"` // if true, send existing events first
	BufferSize        int32                  `protobuf:"varint,5,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`                      // internal buffer size hint
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_analytics_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *StreamEventsRequest) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *StreamEventsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *StreamEventsRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *StreamEventsRequest) GetIncludeHistorical() bool {
	if x != nil {
		return x.IncludeHistorical
	}
	return false
}

func (x *StreamEventsRequest) GetBufferSize() int32 {
	if x != nil {
		return x.BufferSize
	}
	return 0
}

// ExportDataRequest represents a request to export data.
type ExportDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        ExportFormat           `protobuf:"varint,1,opt,name=format,proto3,enum=aegion.analytics.ExportFormat" json:"format,omitempty"`
	Filters       []*Filter              `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	MaxRecords    int64                  `protobuf:"varint,4,opt,name=max_records,json=maxRecords,proto3" json:"max_records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportDataRequest) Reset() {
	*x = ExportDataRequest{}
	mi := &file_analytics_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportDataRequest) ProtoMessage() {}

func (x *ExportDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportDataRequest.ProtoReflect.Descriptor instead.
func (*ExportDataRequest) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *ExportDataRequest) GetFormat() ExportFormat {
	if x != nil {
		return x.Format
	}
	return ExportFormat_EXPORT_FORMAT_UNSPECIFIED
}

func (x *ExportDataRequest) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ExportDataRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ExportDataRequest) GetMaxRecords() int64 {
	if x != nil {
		return x.MaxRecords
	}
	return 0
}

// QueryBatch represents a query in a batch operation.
type QueryBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	QueryId       string                 `protobuf:"bytes,2,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Parameters    []string               `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryBatch) Reset() {
	*x = QueryBatch{}
	mi := &file_analytics_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBatch) ProtoMessage() {}

func (x *QueryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBatch.ProtoReflect.Descriptor instead.
func (*QueryBatch) Descriptor() ([]byte, []int) {
	return file_analytics_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *QueryBatch) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *QueryBatch) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryBatch) GetParameters() []string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *QueryBatch) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_analytics_analytics_proto protoreflect.FileDescriptor

const file_analytics_analytics_proto_rawDesc = "" +
	"\n" +
	"\x19analytics/analytics.proto\x12\x10aegion.analytics\x1a\x1cgoogle/protobuf/struct.proto\x1a\x15analytics/types.proto\"\x9a\x02\n" +
	"\x12QueryEventsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x122\n" +
	"\afilters\x18\x03 \x03(\v2\x18.aegion.analytics.FilterR\afilters\x12\x1d\n" +
	"\n" +
	"sort_field\x18\x04 \x01(\tR\tsortField\x12:\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x0e2\x1b.aegion.analytics.SortOrderR\tsortOrder\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x1d\n" +
	"\n" +
	"event_type\x18\a \x01(\tR\teventType\"\x8f\x01\n" +
	"\x13QueryEventsResponse\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.aegion.analytics.EventR\x06events\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken\"%\n" +
	"\x13GetDashboardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xaf\x01\n" +
	"\rDashboardData\x129\n" +
	"\tdashboard\x18\x01 \x01(\v2\x1b.aegion.analytics.DashboardR\tdashboard\x12/\n" +
	"\x06events\x18\x02 \x03(\v2\x17.aegion.analytics.EventR\x06events\x122\n" +
	"\ametrics\x18\x03 \x03(\v2\x18.aegion.analytics.MetricR\ametrics\"\x8c\x01\n" +
	"\x13ExecuteQueryRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x1e\n" +
	"\n" +
	"parameters\x18\x02 \x03(\tR\n" +
	"parameters\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\x97\x01\n" +
	"\x16CreateDashboardRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06config\x12\x16\n" +
	"\x06public\x18\x04 \x01(\bR\x06public\"\xa7\x01\n" +
	"\x16UpdateDashboardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12/\n" +
	"\x06config\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06config\x12\x16\n" +
	"\x06public\x18\x05 \x01(\bR\x06public\"\xd4\x01\n" +
	"\x13StreamEventsRequest\x122\n" +
	"\afilters\x18\x01 \x03(\v2\x18.aegion.analytics.FilterR\afilters\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12-\n" +
	"\x12include_historical\x18\x04 \x01(\bR\x11includeHistorical\x12\x1f\n" +
	"\vbuffer_size\x18\x05 \x01(\x05R\n" +
	"bufferSize\"\xbc\x01\n" +
	"\x11ExportDataRequest\x126\n" +
	"\x06format\x18\x01 \x01(\x0e2\x1e.aegion.analytics.ExportFormatR\x06format\x122\n" +
	"\afilters\x18\x02 \x03(\v2\x18.aegion.analytics.FilterR\afilters\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1f\n" +
	"\vmax_records\x18\x04 \x01(\x03R\n" +
	"maxRecords\"\x83\x01\n" +
	"\n" +
	"QueryBatch\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bquery_id\x18\x02 \x01(\tR\aqueryId\x12\x1e\n" +
	"\n" +
	"parameters\x18\x03 \x03(\tR\n" +
	"parameters\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize2\x8f\x06\n" +
	"\x10AnalyticsService\x12Z\n" +
	"\vQueryEvents\x12$.aegion.analytics.QueryEventsRequest\x1a%.aegion.analytics.QueryEventsResponse\x12V\n" +
	"\fGetDashboard\x12%.aegion.analytics.GetDashboardRequest\x1a\x1f.aegion.analytics.DashboardData\x12J\n" +
	"\x0fGetHealthStatus\x12\x17.aegion.analytics.Empty\x1a\x1e.aegion.analytics.HealthStatus\x12T\n" +
	"\fExecuteQuery\x12%.aegion.analytics.ExecuteQueryRequest\x1a\x1d.aegion.analytics.QueryResult\x12X\n" +
	"\x0fCreateDashboard\x12(.aegion.analytics.CreateDashboardRequest\x1a\x1b.aegion.analytics.Dashboard\x12X\n" +
	"\x0fUpdateDashboard\x12(.aegion.analytics.UpdateDashboardRequest\x1a\x1b.aegion.analytics.Dashboard\x12P\n" +
	"\fStreamEvents\x12%.aegion.analytics.StreamEventsRequest\x1a\x17.aegion.analytics.Event0\x01\x12P\n" +
	"\n" +
	"ExportData\x12#.aegion.analytics.ExportDataRequest\x1a\x1b.aegion.analytics.DataChunk0\x01\x12M\n" +
	"\n" +
	"BatchQuery\x12\x1c.aegion.analytics.QueryBatch\x1a\x1d.aegion.analytics.QueryResult(\x010\x01B3Z1github.com/aegion/aegion/internal/proto/analyticsb\x06proto3"

var (
	file_analytics_analytics_proto_rawDescOnce sync.Once
	file_analytics_analytics_proto_rawDescData []byte
)

func file_analytics_analytics_proto_rawDescGZIP() []byte {
	file_analytics_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_analytics_proto_rawDesc), len(file_analytics_analytics_proto_rawDesc)))
	})
	return file_analytics_analytics_proto_rawDescData
}

var file_analytics_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_analytics_analytics_proto_goTypes = []any{
	(*QueryEventsRequest)(nil),     // 0: aegion.analytics.QueryEventsRequest
	(*QueryEventsResponse)(nil),    // 1: aegion.analytics.QueryEventsResponse
	(*GetDashboardRequest)(nil),    // 2: aegion.analytics.GetDashboardRequest
	(*DashboardData)(nil),          // 3: aegion.analytics.DashboardData
	(*ExecuteQueryRequest)(nil),    // 4: aegion.analytics.ExecuteQueryRequest
	(*CreateDashboardRequest)(nil), // 5: aegion.analytics.CreateDashboardRequest
	(*UpdateDashboardRequest)(nil), // 6: aegion.analytics.UpdateDashboardRequest
	(*StreamEventsRequest)(nil),    // 7: aegion.analytics.StreamEventsRequest
	(*ExportDataRequest)(nil),      // 8: aegion.analytics.ExportDataRequest
	(*QueryBatch)(nil),             // 9: aegion.analytics.QueryBatch
	(*Filter)(nil),                 // 10: aegion.analytics.Filter
	(SortOrder)(0),                 // 11: aegion.analytics.SortOrder
	(*Event)(nil),                  // 12: aegion.analytics.Event
	(*Dashboard)(nil),              // 13: aegion.analytics.Dashboard
	(*Metric)(nil),                 // 14: aegion.analytics.Metric
	(*structpb.Struct)(nil),        // 15: google.protobuf.Struct
	(ExportFormat)(0),              // 16: aegion.analytics.ExportFormat
	(*Empty)(nil),                  // 17: aegion.analytics.Empty
	(*HealthStatus)(nil),           // 18: aegion.analytics.HealthStatus
	(*QueryResult)(nil),            // 19: aegion.analytics.QueryResult
	(*DataChunk)(nil),              // 20: aegion.analytics.DataChunk
}
var file_analytics_analytics_proto_depIdxs = []int32{
	10, // 0: aegion.analytics.QueryEventsRequest.filters:type_name -> aegion.analytics.Filter
	11, // 1: aegion.analytics.QueryEventsRequest.sort_order:type_name -> aegion.analytics.SortOrder
	12, // 2: aegion.analytics.QueryEventsResponse.events:type_name -> aegion.analytics.Event
	13, // 3: aegion.analytics.DashboardData.dashboard:type_name -> aegion.analytics.Dashboard
	12, // 4: aegion.analytics.DashboardData.events:type_name -> aegion.analytics.Event
	14, // 5: aegion.analytics.DashboardData.metrics:type_name -> aegion.analytics.Metric
	15, // 6: aegion.analytics.CreateDashboardRequest.config:type_name -> google.protobuf.Struct
	15, // 7: aegion.analytics.UpdateDashboardRequest.config:type_name -> google.protobuf.Struct
	10, // 8: aegion.analytics.StreamEventsRequest.filters:type_name -> aegion.analytics.Filter
	16, // 9: aegion.analytics.ExportDataRequest.format:type_name -> aegion.analytics.ExportFormat
	10, // 10: aegion.analytics.ExportDataRequest.filters:type_name -> aegion.analytics.Filter
	0,  // 11: aegion.analytics.AnalyticsService.QueryEvents:input_type -> aegion.analytics.QueryEventsRequest
	2,  // 12: aegion.analytics.AnalyticsService.GetDashboard:input_type -> aegion.analytics.GetDashboardRequest
	17, // 13: aegion.analytics.AnalyticsService.GetHealthStatus:input_type -> aegion.analytics.Empty
	4,  // 14: aegion.analytics.AnalyticsService.ExecuteQuery:input_type -> aegion.analytics.ExecuteQueryRequest
	5,  // 15: aegion.analytics.AnalyticsService.CreateDashboard:input_type -> aegion.analytics.CreateDashboardRequest
	6,  // 16: aegion.analytics.AnalyticsService.UpdateDashboard:input_type -> aegion.analytics.UpdateDashboardRequest
	7,  // 17: aegion.analytics.AnalyticsService.StreamEvents:input_type -> aegion.analytics.StreamEventsRequest
	8,  // 18: aegion.analytics.AnalyticsService.ExportData:input_type -> aegion.analytics.ExportDataRequest
	9,  // 19: aegion.analytics.AnalyticsService.BatchQuery:input_type -> aegion.analytics.QueryBatch
	1,  // 20: aegion.analytics.AnalyticsService.QueryEvents:output_type -> aegion.analytics.QueryEventsResponse
	3,  // 21: aegion.analytics.AnalyticsService.GetDashboard:output_type -> aegion.analytics.DashboardData
	18, // 22: aegion.analytics.AnalyticsService.GetHealthStatus:output_type -> aegion.analytics.HealthStatus
	19, // 23: aegion.analytics.AnalyticsService.ExecuteQuery:output_type -> aegion.analytics.QueryResult
	13, // 24: aegion.analytics.AnalyticsService.CreateDashboard:output_type -> aegion.analytics.Dashboard
	13, // 25: aegion.analytics.AnalyticsService.UpdateDashboard:output_type -> aegion.analytics.Dashboard
	12, // 26: aegion.analytics.AnalyticsService.StreamEvents:output_type -> aegion.analytics.Event
	20, // 27: aegion.analytics.AnalyticsService.ExportData:output_type -> aegion.analytics.DataChunk
	19, // 28: aegion.analytics.AnalyticsService.BatchQuery:output_type -> aegion.analytics.QueryResult
	20, // [20:29] is the sub-list for method output_type
	11, // [11:20] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_analytics_analytics_proto_init() }
func file_analytics_analytics_proto_init() {
	if File_analytics_analytics_proto != nil {
		return
	}
	file_analytics_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_analytics_proto_rawDesc), len(file_analytics_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_analytics_proto_msgTypes,
	}.Build()
	File_analytics_analytics_proto = out.File
	file_analytics_analytics_proto_goTypes = nil
	file_analytics_analytics_proto_depIdxs = nil
}
