// Code generated by hand for beta alignment (grpc scaffold).
// This package intentionally mirrors the minimum surface needed by modules/analytics/grpc.
//
// When a real .proto + protoc pipeline is introduced, this file should be replaced by generated code.
package analytics

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// AnalyticsServiceServer is the server API for AnalyticsService.
type AnalyticsServiceServer interface {
	QueryEvents(context.Context, *QueryEventsRequest) (*QueryEventsResponse, error)
	GetDashboard(context.Context, *GetDashboardRequest) (*DashboardData, error)
	GetHealthStatus(context.Context, *Empty) (*HealthStatus, error)
	ExecuteQuery(context.Context, *ExecuteQueryRequest) (*QueryResult, error)
	CreateDashboard(context.Context, *CreateDashboardRequest) (*Dashboard, error)
	UpdateDashboard(context.Context, *UpdateDashboardRequest) (*Dashboard, error)

	StreamEvents(*StreamEventsRequest, grpc.ServerStream) error
	ExportData(*ExportDataRequest, grpc.ServerStream) error
	BatchQuery(grpc.ServerStream) error

	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer can be embedded for forward compatibility.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) QueryEvents(context.Context, *QueryEventsRequest) (*QueryEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryEvents not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetDashboard(context.Context, *GetDashboardRequest) (*DashboardData, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDashboard not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetHealthStatus(context.Context, *Empty) (*HealthStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHealthStatus not implemented")
}
func (UnimplementedAnalyticsServiceServer) ExecuteQuery(context.Context, *ExecuteQueryRequest) (*QueryResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteQuery not implemented")
}
func (UnimplementedAnalyticsServiceServer) CreateDashboard(context.Context, *CreateDashboardRequest) (*Dashboard, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDashboard not implemented")
}
func (UnimplementedAnalyticsServiceServer) UpdateDashboard(context.Context, *UpdateDashboardRequest) (*Dashboard, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDashboard not implemented")
}
func (UnimplementedAnalyticsServiceServer) StreamEvents(*StreamEventsRequest, grpc.ServerStream) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedAnalyticsServiceServer) ExportData(*ExportDataRequest, grpc.ServerStream) error {
	return status.Error(codes.Unimplemented, "method ExportData not implemented")
}
func (UnimplementedAnalyticsServiceServer) BatchQuery(grpc.ServerStream) error {
	return status.Error(codes.Unimplemented, "method BatchQuery not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}

// RegisterAnalyticsServiceServer registers the service implementation.
func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService.
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aegion.analytics.v1.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "QueryEvents", Handler: _AnalyticsService_QueryEvents_Handler},
		{MethodName: "GetDashboard", Handler: _AnalyticsService_GetDashboard_Handler},
		{MethodName: "GetHealthStatus", Handler: _AnalyticsService_GetHealthStatus_Handler},
		{MethodName: "ExecuteQuery", Handler: _AnalyticsService_ExecuteQuery_Handler},
		{MethodName: "CreateDashboard", Handler: _AnalyticsService_CreateDashboard_Handler},
		{MethodName: "UpdateDashboard", Handler: _AnalyticsService_UpdateDashboard_Handler},
	},
	Streams: []grpc.StreamDesc{
		{StreamName: "StreamEvents", Handler: _AnalyticsService_StreamEvents_Handler, ServerStreams: true},
		{StreamName: "ExportData", Handler: _AnalyticsService_ExportData_Handler, ServerStreams: true},
		{StreamName: "BatchQuery", Handler: _AnalyticsService_BatchQuery_Handler, ServerStreams: true, ClientStreams: true},
	},
	Metadata: "analytics.proto",
}

func _AnalyticsService_QueryEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).QueryEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/aegion.analytics.v1.AnalyticsService/QueryEvents"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).QueryEvents(ctx, req.(*QueryEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/aegion.analytics.v1.AnalyticsService/GetDashboard"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetDashboard(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetHealthStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetHealthStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/aegion.analytics.v1.AnalyticsService/GetHealthStatus"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetHealthStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_ExecuteQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).ExecuteQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/aegion.analytics.v1.AnalyticsService/ExecuteQuery"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).ExecuteQuery(ctx, req.(*ExecuteQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_CreateDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).CreateDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/aegion.analytics.v1.AnalyticsService/CreateDashboard"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).CreateDashboard(ctx, req.(*CreateDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_UpdateDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).UpdateDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/aegion.analytics.v1.AnalyticsService/UpdateDashboard"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).UpdateDashboard(ctx, req.(*UpdateDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	in := new(StreamEventsRequest)
	if err := stream.RecvMsg(in); err != nil {
		return err
	}
	return srv.(AnalyticsServiceServer).StreamEvents(in, stream)
}

func _AnalyticsService_ExportData_Handler(srv interface{}, stream grpc.ServerStream) error {
	in := new(ExportDataRequest)
	if err := stream.RecvMsg(in); err != nil {
		return err
	}
	return srv.(AnalyticsServiceServer).ExportData(in, stream)
}

func _AnalyticsService_BatchQuery_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AnalyticsServiceServer).BatchQuery(stream)
}

