// Code generated by hand for beta alignment (proto scaffold).
// This package intentionally mirrors the minimum surface needed by modules/analytics/grpc.
//
// When a real .proto + protoc pipeline is introduced, this file should be replaced by generated code.
package analytics

import (
	"fmt"

	"google.golang.org/protobuf/types/known/structpb"
)

// ExportFormat represents supported export formats.
type ExportFormat int32

const (
	ExportFormat_JSON    ExportFormat = 0
	ExportFormat_CSV     ExportFormat = 1
	ExportFormat_PARQUET ExportFormat = 2
)

func (f ExportFormat) String() string {
	switch f {
	case ExportFormat_CSV:
		return "CSV"
	case ExportFormat_PARQUET:
		return "PARQUET"
	default:
		return "JSON"
	}
}

// Empty is a placeholder empty message.
type Empty struct{}

// QueryEventsRequest requests event data with optional filters.
type QueryEventsRequest struct {
	PageSize  int32  `json:"page_size,omitempty"`
	PageToken string `json:"page_token,omitempty"`
	Category  string `json:"category,omitempty"`
	EventType string `json:"event_type,omitempty"`
}

// QueryEventsResponse returns event data and paging info.
type QueryEventsResponse struct {
	Events        []*Event `json:"events,omitempty"`
	TotalCount    int64    `json:"total_count,omitempty"`
	NextPageToken string   `json:"next_page_token,omitempty"`
}

// GetDashboardRequest requests a dashboard by ID.
type GetDashboardRequest struct {
	Id string `json:"id,omitempty"`
}

// DashboardData is the response for GetDashboard.
type DashboardData struct {
	Dashboard *Dashboard `json:"dashboard,omitempty"`
	Events    []*Event   `json:"events,omitempty"`
	Metrics   []*Metric  `json:"metrics,omitempty"`
}

// ExecuteQueryRequest requests execution of a saved query.
type ExecuteQueryRequest struct {
	QueryId   string `json:"query_id,omitempty"`
	PageSize  int32  `json:"page_size,omitempty"`
	PageToken string `json:"page_token,omitempty"`
}

// QueryResult represents a query execution result.
type QueryResult struct {
	Id       string `json:"id,omitempty"`
	RowCount int64  `json:"row_count,omitempty"`
}

// CreateDashboardRequest requests creation of a dashboard.
type CreateDashboardRequest struct {
	Name        string          `json:"name,omitempty"`
	Description string          `json:"description,omitempty"`
	Config      *structpb.Struct `json:"config,omitempty"`
	Public      bool            `json:"public,omitempty"`
}

// UpdateDashboardRequest requests updating a dashboard.
type UpdateDashboardRequest struct {
	Id          string          `json:"id,omitempty"`
	Name        string          `json:"name,omitempty"`
	Description string          `json:"description,omitempty"`
	Config      *structpb.Struct `json:"config,omitempty"`
	Public      bool            `json:"public,omitempty"`
}

// StreamEventsRequest requests streaming of events.
type StreamEventsRequest struct {
	Category          string `json:"category,omitempty"`
	IncludeHistorical bool   `json:"include_historical,omitempty"`
}

// ExportDataRequest requests export of event data.
type ExportDataRequest struct {
	Format     ExportFormat `json:"format,omitempty"`
	MaxRecords int64        `json:"max_records,omitempty"`
	Category   string       `json:"category,omitempty"`
}

// DataChunk is streamed for exports.
type DataChunk struct {
	Data     []byte `json:"data,omitempty"`
	Sequence int32  `json:"sequence,omitempty"`
	IsFinal  bool   `json:"is_final,omitempty"`
}

// QueryBatch is used for bidirectional batch query streaming.
type QueryBatch struct {
	RequestId string `json:"request_id,omitempty"`
	QueryId   string `json:"query_id,omitempty"`
}

// Event represents an analytics event.
type Event struct {
	Id        string `json:"id,omitempty"`
	Category  string `json:"category,omitempty"`
	EventType string `json:"event_type,omitempty"`
}

// Metric represents a metric datapoint (minimal for grpc slice).
type Metric struct {
	Name  string  `json:"name,omitempty"`
	Value float64 `json:"value,omitempty"`
}

// Dashboard represents a dashboard definition (minimal for grpc slice).
type Dashboard struct {
	Id          string `json:"id,omitempty"`
	Name        string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	OwnerId     string `json:"owner_id,omitempty"`
	Public      bool   `json:"public,omitempty"`
}

// HealthStatus represents current health status.
type HealthStatus struct {
	IsHealthy      bool   `json:"is_healthy,omitempty"`
	Status         string `json:"status,omitempty"`
	Duckdb         bool   `json:"duckdb,omitempty"`
	Storage        bool   `json:"storage,omitempty"`
	Migrations     bool   `json:"migrations,omitempty"`
	SyncLagSeconds int64  `json:"sync_lag_seconds,omitempty"`
}

func (r *CreateDashboardRequest) GetConfig() *structpb.Struct {
	if r == nil {
		return nil
	}
	return r.Config
}

func (r *UpdateDashboardRequest) GetConfig() *structpb.Struct {
	if r == nil {
		return nil
	}
	return r.Config
}

func (r *ExportDataRequest) GetFormat() ExportFormat {
	if r == nil {
		return ExportFormat_JSON
	}
	return r.Format
}

func (r *GetDashboardRequest) String() string {
	return fmt.Sprintf("GetDashboardRequest{id=%q}", r.Id)
}

