// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: policy/policy.proto

package policypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PolicyEngine_Check_FullMethodName      = "/aegion.policy.v1.PolicyEngine/Check"
	PolicyEngine_BatchCheck_FullMethodName = "/aegion.policy.v1.PolicyEngine/BatchCheck"
)

// PolicyEngineClient is the client API for PolicyEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PolicyEngine evaluates authorization decisions across RBAC/ABAC/ReBAC models.
type PolicyEngineClient interface {
	// Check evaluates a single authorization decision.
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	// BatchCheck evaluates multiple authorization decisions in one call.
	BatchCheck(ctx context.Context, in *BatchCheckRequest, opts ...grpc.CallOption) (*BatchCheckResponse, error)
}

type policyEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyEngineClient(cc grpc.ClientConnInterface) PolicyEngineClient {
	return &policyEngineClient{cc}
}

func (c *policyEngineClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, PolicyEngine_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyEngineClient) BatchCheck(ctx context.Context, in *BatchCheckRequest, opts ...grpc.CallOption) (*BatchCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCheckResponse)
	err := c.cc.Invoke(ctx, PolicyEngine_BatchCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyEngineServer is the server API for PolicyEngine service.
// All implementations must embed UnimplementedPolicyEngineServer
// for forward compatibility.
//
// PolicyEngine evaluates authorization decisions across RBAC/ABAC/ReBAC models.
type PolicyEngineServer interface {
	// Check evaluates a single authorization decision.
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	// BatchCheck evaluates multiple authorization decisions in one call.
	BatchCheck(context.Context, *BatchCheckRequest) (*BatchCheckResponse, error)
	mustEmbedUnimplementedPolicyEngineServer()
}

// UnimplementedPolicyEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicyEngineServer struct{}

func (UnimplementedPolicyEngineServer) Check(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedPolicyEngineServer) BatchCheck(context.Context, *BatchCheckRequest) (*BatchCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchCheck not implemented")
}
func (UnimplementedPolicyEngineServer) mustEmbedUnimplementedPolicyEngineServer() {}
func (UnimplementedPolicyEngineServer) testEmbeddedByValue()                      {}

// UnsafePolicyEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyEngineServer will
// result in compilation errors.
type UnsafePolicyEngineServer interface {
	mustEmbedUnimplementedPolicyEngineServer()
}

func RegisterPolicyEngineServer(s grpc.ServiceRegistrar, srv PolicyEngineServer) {
	// If the following call pancis, it indicates UnimplementedPolicyEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolicyEngine_ServiceDesc, srv)
}

func _PolicyEngine_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyEngineServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyEngine_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyEngineServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyEngine_BatchCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyEngineServer).BatchCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyEngine_BatchCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyEngineServer).BatchCheck(ctx, req.(*BatchCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PolicyEngine_ServiceDesc is the grpc.ServiceDesc for PolicyEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aegion.policy.v1.PolicyEngine",
	HandlerType: (*PolicyEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _PolicyEngine_Check_Handler,
		},
		{
			MethodName: "BatchCheck",
			Handler:    _PolicyEngine_BatchCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "policy/policy.proto",
}
