// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: policy/policy.proto

package policypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subject identifier, for example: "user:alice".
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	// Resource identifier, for example: "document:spec-123".
	Resource string `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// Resource type, for example: "documents".
	ResourceType string `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	// Action identifier, for example: "read".
	Action string `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	// Optional model override: rbac | abac | rebac.
	Model string `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	// Evaluation context passed by caller.
	Context       *Context `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_policy_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_policy_policy_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CheckRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CheckRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *CheckRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CheckRequest) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

type CheckResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Allowed bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// Which model produced the final decision.
	ModelUsed string `protobuf:"bytes,2,opt,name=model_used,json=modelUsed,proto3" json:"model_used,omitempty"`
	// Human-readable deny reason for diagnostics.
	DenyReason string `protobuf:"bytes,3,opt,name=deny_reason,json=denyReason,proto3" json:"deny_reason,omitempty"`
	// Ordered evaluation trace (low-cardinality step identifiers).
	EvalPath      []string `protobuf:"bytes,4,rep,name=eval_path,json=evalPath,proto3" json:"eval_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_policy_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_policy_policy_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResponse) GetModelUsed() string {
	if x != nil {
		return x.ModelUsed
	}
	return ""
}

func (x *CheckResponse) GetDenyReason() string {
	if x != nil {
		return x.DenyReason
	}
	return ""
}

func (x *CheckResponse) GetEvalPath() []string {
	if x != nil {
		return x.EvalPath
	}
	return nil
}

type BatchCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checks        []*CheckRequest        `protobuf:"bytes,1,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckRequest) Reset() {
	*x = BatchCheckRequest{}
	mi := &file_policy_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckRequest) ProtoMessage() {}

func (x *BatchCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckRequest.ProtoReflect.Descriptor instead.
func (*BatchCheckRequest) Descriptor() ([]byte, []int) {
	return file_policy_policy_proto_rawDescGZIP(), []int{2}
}

func (x *BatchCheckRequest) GetChecks() []*CheckRequest {
	if x != nil {
		return x.Checks
	}
	return nil
}

type BatchCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*CheckResponse       `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCheckResponse) Reset() {
	*x = BatchCheckResponse{}
	mi := &file_policy_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCheckResponse) ProtoMessage() {}

func (x *BatchCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCheckResponse.ProtoReflect.Descriptor instead.
func (*BatchCheckResponse) Descriptor() ([]byte, []int) {
	return file_policy_policy_proto_rawDescGZIP(), []int{3}
}

func (x *BatchCheckResponse) GetResults() []*CheckResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

type Context struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client IP address.
	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	// Request time.
	Time *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	// Optional tenant identifier.
	TenantId string `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Additional caller-defined context attributes.
	Extra         map[string]string `protobuf:"bytes,4,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_policy_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_policy_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_policy_policy_proto_rawDescGZIP(), []int{4}
}

func (x *Context) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Context) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Context) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Context) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

var File_policy_policy_proto protoreflect.FileDescriptor

const file_policy_policy_proto_rawDesc = "" +
	"\n" +
	"\x13policy/policy.proto\x12\x10aegion.policy.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcc\x01\n" +
	"\fCheckRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x123\n" +
	"\acontext\x18\x06 \x01(\v2\x19.aegion.policy.v1.ContextR\acontext\"\x86\x01\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1d\n" +
	"\n" +
	"model_used\x18\x02 \x01(\tR\tmodelUsed\x12\x1f\n" +
	"\vdeny_reason\x18\x03 \x01(\tR\n" +
	"denyReason\x12\x1b\n" +
	"\teval_path\x18\x04 \x03(\tR\bevalPath\"K\n" +
	"\x11BatchCheckRequest\x126\n" +
	"\x06checks\x18\x01 \x03(\v2\x1e.aegion.policy.v1.CheckRequestR\x06checks\"O\n" +
	"\x12BatchCheckResponse\x129\n" +
	"\aresults\x18\x01 \x03(\v2\x1f.aegion.policy.v1.CheckResponseR\aresults\"\xdc\x01\n" +
	"\aContext\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12:\n" +
	"\x05extra\x18\x04 \x03(\v2$.aegion.policy.v1.Context.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xb1\x01\n" +
	"\fPolicyEngine\x12H\n" +
	"\x05Check\x12\x1e.aegion.policy.v1.CheckRequest\x1a\x1f.aegion.policy.v1.CheckResponse\x12W\n" +
	"\n" +
	"BatchCheck\x12#.aegion.policy.v1.BatchCheckRequest\x1a$.aegion.policy.v1.BatchCheckResponseB<Z:github.com/aegion/aegion/internal/proto/policy/v1;policypbb\x06proto3"

var (
	file_policy_policy_proto_rawDescOnce sync.Once
	file_policy_policy_proto_rawDescData []byte
)

func file_policy_policy_proto_rawDescGZIP() []byte {
	file_policy_policy_proto_rawDescOnce.Do(func() {
		file_policy_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_policy_policy_proto_rawDesc), len(file_policy_policy_proto_rawDesc)))
	})
	return file_policy_policy_proto_rawDescData
}

var file_policy_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_policy_policy_proto_goTypes = []any{
	(*CheckRequest)(nil),          // 0: aegion.policy.v1.CheckRequest
	(*CheckResponse)(nil),         // 1: aegion.policy.v1.CheckResponse
	(*BatchCheckRequest)(nil),     // 2: aegion.policy.v1.BatchCheckRequest
	(*BatchCheckResponse)(nil),    // 3: aegion.policy.v1.BatchCheckResponse
	(*Context)(nil),               // 4: aegion.policy.v1.Context
	nil,                           // 5: aegion.policy.v1.Context.ExtraEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_policy_policy_proto_depIdxs = []int32{
	4, // 0: aegion.policy.v1.CheckRequest.context:type_name -> aegion.policy.v1.Context
	0, // 1: aegion.policy.v1.BatchCheckRequest.checks:type_name -> aegion.policy.v1.CheckRequest
	1, // 2: aegion.policy.v1.BatchCheckResponse.results:type_name -> aegion.policy.v1.CheckResponse
	6, // 3: aegion.policy.v1.Context.time:type_name -> google.protobuf.Timestamp
	5, // 4: aegion.policy.v1.Context.extra:type_name -> aegion.policy.v1.Context.ExtraEntry
	0, // 5: aegion.policy.v1.PolicyEngine.Check:input_type -> aegion.policy.v1.CheckRequest
	2, // 6: aegion.policy.v1.PolicyEngine.BatchCheck:input_type -> aegion.policy.v1.BatchCheckRequest
	1, // 7: aegion.policy.v1.PolicyEngine.Check:output_type -> aegion.policy.v1.CheckResponse
	3, // 8: aegion.policy.v1.PolicyEngine.BatchCheck:output_type -> aegion.policy.v1.BatchCheckResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_policy_policy_proto_init() }
func file_policy_policy_proto_init() {
	if File_policy_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_policy_policy_proto_rawDesc), len(file_policy_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_policy_policy_proto_goTypes,
		DependencyIndexes: file_policy_policy_proto_depIdxs,
		MessageInfos:      file_policy_policy_proto_msgTypes,
	}.Build()
	File_policy_policy_proto = out.File
	file_policy_policy_proto_goTypes = nil
	file_policy_policy_proto_depIdxs = nil
}
