// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.3
// source: core/courier.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MESSAGE_TYPE_EMAIL       MessageType = 1
	MessageType_MESSAGE_TYPE_SMS         MessageType = 2
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_EMAIL",
		2: "MESSAGE_TYPE_SMS",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"MESSAGE_TYPE_EMAIL":       1,
		"MESSAGE_TYPE_SMS":         2,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_core_courier_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_core_courier_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_core_courier_proto_rawDescGZIP(), []int{0}
}

type DeliveryStatus int32

const (
	DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED DeliveryStatus = 0
	DeliveryStatus_DELIVERY_STATUS_QUEUED      DeliveryStatus = 1
	DeliveryStatus_DELIVERY_STATUS_PROCESSING  DeliveryStatus = 2
	DeliveryStatus_DELIVERY_STATUS_SENT        DeliveryStatus = 3
	DeliveryStatus_DELIVERY_STATUS_FAILED      DeliveryStatus = 4
	DeliveryStatus_DELIVERY_STATUS_ABANDONED   DeliveryStatus = 5
	DeliveryStatus_DELIVERY_STATUS_CANCELLED   DeliveryStatus = 6
)

// Enum value maps for DeliveryStatus.
var (
	DeliveryStatus_name = map[int32]string{
		0: "DELIVERY_STATUS_UNSPECIFIED",
		1: "DELIVERY_STATUS_QUEUED",
		2: "DELIVERY_STATUS_PROCESSING",
		3: "DELIVERY_STATUS_SENT",
		4: "DELIVERY_STATUS_FAILED",
		5: "DELIVERY_STATUS_ABANDONED",
		6: "DELIVERY_STATUS_CANCELLED",
	}
	DeliveryStatus_value = map[string]int32{
		"DELIVERY_STATUS_UNSPECIFIED": 0,
		"DELIVERY_STATUS_QUEUED":      1,
		"DELIVERY_STATUS_PROCESSING":  2,
		"DELIVERY_STATUS_SENT":        3,
		"DELIVERY_STATUS_FAILED":      4,
		"DELIVERY_STATUS_ABANDONED":   5,
		"DELIVERY_STATUS_CANCELLED":   6,
	}
)

func (x DeliveryStatus) Enum() *DeliveryStatus {
	p := new(DeliveryStatus)
	*p = x
	return p
}

func (x DeliveryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_core_courier_proto_enumTypes[1].Descriptor()
}

func (DeliveryStatus) Type() protoreflect.EnumType {
	return &file_core_courier_proto_enumTypes[1]
}

func (x DeliveryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryStatus.Descriptor instead.
func (DeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return file_core_courier_proto_rawDescGZIP(), []int{1}
}

type EnqueueRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message type
	Type MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=aegion.core.courier.MessageType" json:"type,omitempty"`
	// Recipient address (email or phone)
	Recipient string `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// Template ID (e.g., "verification_code", "password_reset")
	TemplateId string `protobuf:"bytes,3,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	// Template data for rendering
	TemplateData map[string]string `protobuf:"bytes,4,rep,name=template_data,json=templateData,proto3" json:"template_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Idempotency key to prevent duplicate sends
	IdempotencyKey string `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Optional: send after this timestamp
	SendAfter int64 `protobuf:"varint,6,opt,name=send_after,json=sendAfter,proto3" json:"send_after,omitempty"`
	// Optional: custom subject (email only)
	Subject string `protobuf:"bytes,7,opt,name=subject,proto3" json:"subject,omitempty"`
	// Source module requesting the send
	SourceModule string `protobuf:"bytes,8,opt,name=source_module,json=sourceModule,proto3" json:"source_module,omitempty"`
	// Related identity ID (for audit)
	IdentityId    string `protobuf:"bytes,9,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueRequest) Reset() {
	*x = EnqueueRequest{}
	mi := &file_core_courier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequest) ProtoMessage() {}

func (x *EnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_courier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return file_core_courier_proto_rawDescGZIP(), []int{0}
}

func (x *EnqueueRequest) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *EnqueueRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *EnqueueRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *EnqueueRequest) GetTemplateData() map[string]string {
	if x != nil {
		return x.TemplateData
	}
	return nil
}

func (x *EnqueueRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *EnqueueRequest) GetSendAfter() int64 {
	if x != nil {
		return x.SendAfter
	}
	return 0
}

func (x *EnqueueRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EnqueueRequest) GetSourceModule() string {
	if x != nil {
		return x.SourceModule
	}
	return ""
}

func (x *EnqueueRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

type EnqueueResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message ID for tracking
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Whether enqueue succeeded
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if failed
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// If idempotency_key matched an existing message
	Deduplicated  bool `protobuf:"varint,4,opt,name=deduplicated,proto3" json:"deduplicated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueResponse) Reset() {
	*x = EnqueueResponse{}
	mi := &file_core_courier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueResponse) ProtoMessage() {}

func (x *EnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_courier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueResponse.ProtoReflect.Descriptor instead.
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return file_core_courier_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EnqueueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnqueueResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *EnqueueResponse) GetDeduplicated() bool {
	if x != nil {
		return x.Deduplicated
	}
	return false
}

type GetStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message ID to check
	MessageId     string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_core_courier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_courier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_core_courier_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatusRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type GetStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message ID
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Current status
	Status DeliveryStatus `protobuf:"varint,2,opt,name=status,proto3,enum=aegion.core.courier.DeliveryStatus" json:"status,omitempty"`
	// Number of send attempts
	SendCount int32 `protobuf:"varint,3,opt,name=send_count,json=sendCount,proto3" json:"send_count,omitempty"`
	// Last error if failed
	LastError string `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	// When the message was sent (if sent)
	SentAt int64 `protobuf:"varint,5,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	// When the message was created
	CreatedAt     int64 `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_core_courier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_courier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_core_courier_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GetStatusResponse) GetStatus() DeliveryStatus {
	if x != nil {
		return x.Status
	}
	return DeliveryStatus_DELIVERY_STATUS_UNSPECIFIED
}

func (x *GetStatusResponse) GetSendCount() int32 {
	if x != nil {
		return x.SendCount
	}
	return 0
}

func (x *GetStatusResponse) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *GetStatusResponse) GetSentAt() int64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

func (x *GetStatusResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CancelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message ID to cancel
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Reason for cancellation
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_core_courier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_courier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_core_courier_proto_rawDescGZIP(), []int{4}
}

func (x *CancelRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *CancelRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether cancellation succeeded
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if failed (e.g., already sent)
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_core_courier_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_courier_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_core_courier_proto_rawDescGZIP(), []int{5}
}

func (x *CancelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_core_courier_proto protoreflect.FileDescriptor

const file_core_courier_proto_rawDesc = "" +
	"\n" +
	"\x12core/courier.proto\x12\x13aegion.core.courier\"\xca\x03\n" +
	"\x0eEnqueueRequest\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2 .aegion.core.courier.MessageTypeR\x04type\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12\x1f\n" +
	"\vtemplate_id\x18\x03 \x01(\tR\n" +
	"templateId\x12Z\n" +
	"\rtemplate_data\x18\x04 \x03(\v25.aegion.core.courier.EnqueueRequest.TemplateDataEntryR\ftemplateData\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12\x1d\n" +
	"\n" +
	"send_after\x18\x06 \x01(\x03R\tsendAfter\x12\x18\n" +
	"\asubject\x18\a \x01(\tR\asubject\x12#\n" +
	"\rsource_module\x18\b \x01(\tR\fsourceModule\x12\x1f\n" +
	"\videntity_id\x18\t \x01(\tR\n" +
	"identityId\x1a?\n" +
	"\x11TemplateDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x01\n" +
	"\x0fEnqueueResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\"\n" +
	"\fdeduplicated\x18\x04 \x01(\bR\fdeduplicated\"1\n" +
	"\x10GetStatusRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"\xe5\x01\n" +
	"\x11GetStatusResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12;\n" +
	"\x06status\x18\x02 \x01(\x0e2#.aegion.core.courier.DeliveryStatusR\x06status\x12\x1d\n" +
	"\n" +
	"send_count\x18\x03 \x01(\x05R\tsendCount\x12\x1d\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tR\tlastError\x12\x17\n" +
	"\asent_at\x18\x05 \x01(\x03R\x06sentAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"F\n" +
	"\rCancelRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"@\n" +
	"\x0eCancelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*Y\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12MESSAGE_TYPE_EMAIL\x10\x01\x12\x14\n" +
	"\x10MESSAGE_TYPE_SMS\x10\x02*\xe1\x01\n" +
	"\x0eDeliveryStatus\x12\x1f\n" +
	"\x1bDELIVERY_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DELIVERY_STATUS_QUEUED\x10\x01\x12\x1e\n" +
	"\x1aDELIVERY_STATUS_PROCESSING\x10\x02\x12\x18\n" +
	"\x14DELIVERY_STATUS_SENT\x10\x03\x12\x1a\n" +
	"\x16DELIVERY_STATUS_FAILED\x10\x04\x12\x1d\n" +
	"\x19DELIVERY_STATUS_ABANDONED\x10\x05\x12\x1d\n" +
	"\x19DELIVERY_STATUS_CANCELLED\x10\x062\x95\x02\n" +
	"\x0eCourierService\x12T\n" +
	"\aEnqueue\x12#.aegion.core.courier.EnqueueRequest\x1a$.aegion.core.courier.EnqueueResponse\x12Z\n" +
	"\tGetStatus\x12%.aegion.core.courier.GetStatusRequest\x1a&.aegion.core.courier.GetStatusResponse\x12Q\n" +
	"\x06Cancel\x12\".aegion.core.courier.CancelRequest\x1a#.aegion.core.courier.CancelResponseB.Z,github.com/aegion/aegion/internal/proto/coreb\x06proto3"

var (
	file_core_courier_proto_rawDescOnce sync.Once
	file_core_courier_proto_rawDescData []byte
)

func file_core_courier_proto_rawDescGZIP() []byte {
	file_core_courier_proto_rawDescOnce.Do(func() {
		file_core_courier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_courier_proto_rawDesc), len(file_core_courier_proto_rawDesc)))
	})
	return file_core_courier_proto_rawDescData
}

var file_core_courier_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_core_courier_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_core_courier_proto_goTypes = []any{
	(MessageType)(0),          // 0: aegion.core.courier.MessageType
	(DeliveryStatus)(0),       // 1: aegion.core.courier.DeliveryStatus
	(*EnqueueRequest)(nil),    // 2: aegion.core.courier.EnqueueRequest
	(*EnqueueResponse)(nil),   // 3: aegion.core.courier.EnqueueResponse
	(*GetStatusRequest)(nil),  // 4: aegion.core.courier.GetStatusRequest
	(*GetStatusResponse)(nil), // 5: aegion.core.courier.GetStatusResponse
	(*CancelRequest)(nil),     // 6: aegion.core.courier.CancelRequest
	(*CancelResponse)(nil),    // 7: aegion.core.courier.CancelResponse
	nil,                       // 8: aegion.core.courier.EnqueueRequest.TemplateDataEntry
}
var file_core_courier_proto_depIdxs = []int32{
	0, // 0: aegion.core.courier.EnqueueRequest.type:type_name -> aegion.core.courier.MessageType
	8, // 1: aegion.core.courier.EnqueueRequest.template_data:type_name -> aegion.core.courier.EnqueueRequest.TemplateDataEntry
	1, // 2: aegion.core.courier.GetStatusResponse.status:type_name -> aegion.core.courier.DeliveryStatus
	2, // 3: aegion.core.courier.CourierService.Enqueue:input_type -> aegion.core.courier.EnqueueRequest
	4, // 4: aegion.core.courier.CourierService.GetStatus:input_type -> aegion.core.courier.GetStatusRequest
	6, // 5: aegion.core.courier.CourierService.Cancel:input_type -> aegion.core.courier.CancelRequest
	3, // 6: aegion.core.courier.CourierService.Enqueue:output_type -> aegion.core.courier.EnqueueResponse
	5, // 7: aegion.core.courier.CourierService.GetStatus:output_type -> aegion.core.courier.GetStatusResponse
	7, // 8: aegion.core.courier.CourierService.Cancel:output_type -> aegion.core.courier.CancelResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_core_courier_proto_init() }
func file_core_courier_proto_init() {
	if File_core_courier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_courier_proto_rawDesc), len(file_core_courier_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_courier_proto_goTypes,
		DependencyIndexes: file_core_courier_proto_depIdxs,
		EnumInfos:         file_core_courier_proto_enumTypes,
		MessageInfos:      file_core_courier_proto_msgTypes,
	}.Build()
	File_core_courier_proto = out.File
	file_core_courier_proto_goTypes = nil
	file_core_courier_proto_depIdxs = nil
}
