// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: core/events.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event type (e.g., "identity.created", "session.revoked")
	EventType string `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Source module publishing the event
	SourceModule string `protobuf:"bytes,2,opt,name=source_module,json=sourceModule,proto3" json:"source_module,omitempty"`
	// Entity type (e.g., "identity", "session")
	EntityType string `protobuf:"bytes,3,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	// Entity ID
	EntityId string `protobuf:"bytes,4,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	// Event payload (JSON encoded)
	Payload []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	// Additional metadata
	Metadata      map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_core_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_core_events_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PublishRequest) GetSourceModule() string {
	if x != nil {
		return x.SourceModule
	}
	return ""
}

func (x *PublishRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *PublishRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *PublishRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PublishRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PublishResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event ID assigned by the bus
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Whether publish succeeded
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if failed
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_core_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_core_events_proto_rawDescGZIP(), []int{1}
}

func (x *PublishResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PublishResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module name subscribing
	Subscriber string `protobuf:"bytes,1,opt,name=subscriber,proto3" json:"subscriber,omitempty"`
	// Event types to subscribe to (empty = all)
	EventTypes []string `protobuf:"bytes,2,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	// Entity types to filter by (empty = all)
	EntityTypes []string `protobuf:"bytes,3,rep,name=entity_types,json=entityTypes,proto3" json:"entity_types,omitempty"`
	// Resume from this event ID (for reconnection)
	ResumeFrom    string `protobuf:"bytes,4,opt,name=resume_from,json=resumeFrom,proto3" json:"resume_from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_core_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_core_events_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetSubscriber() string {
	if x != nil {
		return x.Subscriber
	}
	return ""
}

func (x *SubscribeRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *SubscribeRequest) GetEntityTypes() []string {
	if x != nil {
		return x.EntityTypes
	}
	return nil
}

func (x *SubscribeRequest) GetResumeFrom() string {
	if x != nil {
		return x.ResumeFrom
	}
	return ""
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique event ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Event type
	EventType string `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Source module
	SourceModule string `protobuf:"bytes,3,opt,name=source_module,json=sourceModule,proto3" json:"source_module,omitempty"`
	// Entity type
	EntityType string `protobuf:"bytes,4,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	// Entity ID
	EntityId string `protobuf:"bytes,5,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	// Identity ID (if applicable)
	IdentityId string `protobuf:"bytes,6,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	// Event payload (JSON encoded)
	Payload []byte `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	// Event metadata
	Metadata map[string]string `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// When the event occurred
	OccurredAt int64 `protobuf:"varint,9,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// Delivery attempt number
	Attempt       int32 `protobuf:"varint,10,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_core_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_core_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_core_events_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Event) GetSourceModule() string {
	if x != nil {
		return x.SourceModule
	}
	return ""
}

func (x *Event) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *Event) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Event) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Event) GetOccurredAt() int64 {
	if x != nil {
		return x.OccurredAt
	}
	return 0
}

func (x *Event) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type AcknowledgeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subscriber module
	Subscriber string `protobuf:"bytes,1,opt,name=subscriber,proto3" json:"subscriber,omitempty"`
	// Event ID to acknowledge
	EventId string `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Whether processing succeeded
	Success bool `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if processing failed
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeRequest) Reset() {
	*x = AcknowledgeRequest{}
	mi := &file_core_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeRequest) ProtoMessage() {}

func (x *AcknowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeRequest) Descriptor() ([]byte, []int) {
	return file_core_events_proto_rawDescGZIP(), []int{4}
}

func (x *AcknowledgeRequest) GetSubscriber() string {
	if x != nil {
		return x.Subscriber
	}
	return ""
}

func (x *AcknowledgeRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AcknowledgeRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AcknowledgeRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AcknowledgeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether acknowledge was recorded
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeResponse) Reset() {
	*x = AcknowledgeResponse{}
	mi := &file_core_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeResponse) ProtoMessage() {}

func (x *AcknowledgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeResponse.ProtoReflect.Descriptor instead.
func (*AcknowledgeResponse) Descriptor() ([]byte, []int) {
	return file_core_events_proto_rawDescGZIP(), []int{5}
}

func (x *AcknowledgeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_core_events_proto protoreflect.FileDescriptor

const file_core_events_proto_rawDesc = "" +
	"\n" +
	"\x11core/events.proto\x12\x12aegion.core.events\"\xb7\x02\n" +
	"\x0ePublishRequest\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12#\n" +
	"\rsource_module\x18\x02 \x01(\tR\fsourceModule\x12\x1f\n" +
	"\ventity_type\x18\x03 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x04 \x01(\tR\bentityId\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12L\n" +
	"\bmetadata\x18\x06 \x03(\v20.aegion.core.events.PublishRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\x0fPublishResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x97\x01\n" +
	"\x10SubscribeRequest\x12\x1e\n" +
	"\n" +
	"subscriber\x18\x01 \x01(\tR\n" +
	"subscriber\x12\x1f\n" +
	"\vevent_types\x18\x02 \x03(\tR\n" +
	"eventTypes\x12!\n" +
	"\fentity_types\x18\x03 \x03(\tR\ventityTypes\x12\x1f\n" +
	"\vresume_from\x18\x04 \x01(\tR\n" +
	"resumeFrom\"\x91\x03\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12#\n" +
	"\rsource_module\x18\x03 \x01(\tR\fsourceModule\x12\x1f\n" +
	"\ventity_type\x18\x04 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x05 \x01(\tR\bentityId\x12\x1f\n" +
	"\videntity_id\x18\x06 \x01(\tR\n" +
	"identityId\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12C\n" +
	"\bmetadata\x18\b \x03(\v2'.aegion.core.events.Event.MetadataEntryR\bmetadata\x12\x1f\n" +
	"\voccurred_at\x18\t \x01(\x03R\n" +
	"occurredAt\x12\x18\n" +
	"\aattempt\x18\n" +
	" \x01(\x05R\aattempt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x7f\n" +
	"\x12AcknowledgeRequest\x12\x1e\n" +
	"\n" +
	"subscriber\x18\x01 \x01(\tR\n" +
	"subscriber\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"/\n" +
	"\x13AcknowledgeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x95\x02\n" +
	"\x0fEventBusService\x12R\n" +
	"\aPublish\x12\".aegion.core.events.PublishRequest\x1a#.aegion.core.events.PublishResponse\x12N\n" +
	"\tSubscribe\x12$.aegion.core.events.SubscribeRequest\x1a\x19.aegion.core.events.Event0\x01\x12^\n" +
	"\vAcknowledge\x12&.aegion.core.events.AcknowledgeRequest\x1a'.aegion.core.events.AcknowledgeResponseB.Z,github.com/aegion/aegion/internal/proto/coreb\x06proto3"

var (
	file_core_events_proto_rawDescOnce sync.Once
	file_core_events_proto_rawDescData []byte
)

func file_core_events_proto_rawDescGZIP() []byte {
	file_core_events_proto_rawDescOnce.Do(func() {
		file_core_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_events_proto_rawDesc), len(file_core_events_proto_rawDesc)))
	})
	return file_core_events_proto_rawDescData
}

var file_core_events_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_core_events_proto_goTypes = []any{
	(*PublishRequest)(nil),      // 0: aegion.core.events.PublishRequest
	(*PublishResponse)(nil),     // 1: aegion.core.events.PublishResponse
	(*SubscribeRequest)(nil),    // 2: aegion.core.events.SubscribeRequest
	(*Event)(nil),               // 3: aegion.core.events.Event
	(*AcknowledgeRequest)(nil),  // 4: aegion.core.events.AcknowledgeRequest
	(*AcknowledgeResponse)(nil), // 5: aegion.core.events.AcknowledgeResponse
	nil,                         // 6: aegion.core.events.PublishRequest.MetadataEntry
	nil,                         // 7: aegion.core.events.Event.MetadataEntry
}
var file_core_events_proto_depIdxs = []int32{
	6, // 0: aegion.core.events.PublishRequest.metadata:type_name -> aegion.core.events.PublishRequest.MetadataEntry
	7, // 1: aegion.core.events.Event.metadata:type_name -> aegion.core.events.Event.MetadataEntry
	0, // 2: aegion.core.events.EventBusService.Publish:input_type -> aegion.core.events.PublishRequest
	2, // 3: aegion.core.events.EventBusService.Subscribe:input_type -> aegion.core.events.SubscribeRequest
	4, // 4: aegion.core.events.EventBusService.Acknowledge:input_type -> aegion.core.events.AcknowledgeRequest
	1, // 5: aegion.core.events.EventBusService.Publish:output_type -> aegion.core.events.PublishResponse
	3, // 6: aegion.core.events.EventBusService.Subscribe:output_type -> aegion.core.events.Event
	5, // 7: aegion.core.events.EventBusService.Acknowledge:output_type -> aegion.core.events.AcknowledgeResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_events_proto_init() }
func file_core_events_proto_init() {
	if File_core_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_events_proto_rawDesc), len(file_core_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_events_proto_goTypes,
		DependencyIndexes: file_core_events_proto_depIdxs,
		MessageInfos:      file_core_events_proto_msgTypes,
	}.Build()
	File_core_events_proto = out.File
	file_core_events_proto_goTypes = nil
	file_core_events_proto_depIdxs = nil
}
