// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.3
// source: core/internal_token.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token to validate
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Module presenting the token
	Module        string `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_core_internal_token_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_internal_token_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_core_internal_token_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ValidateRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

type ValidateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the token is valid
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// Error code if invalid
	ErrorCode string `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// Human-readable error message
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Token metadata if valid
	Metadata      *TokenMetadata `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_core_internal_token_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_internal_token_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_core_internal_token_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ValidateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ValidateResponse) GetMetadata() *TokenMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TokenMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When the token was issued
	IssuedAt int64 `protobuf:"varint,1,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	// When the token expires
	ExpiresAt int64 `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Token generation (for rotation tracking)
	Generation    int32 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenMetadata) Reset() {
	*x = TokenMetadata{}
	mi := &file_core_internal_token_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenMetadata) ProtoMessage() {}

func (x *TokenMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_core_internal_token_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenMetadata.ProtoReflect.Descriptor instead.
func (*TokenMetadata) Descriptor() ([]byte, []int) {
	return file_core_internal_token_proto_rawDescGZIP(), []int{2}
}

func (x *TokenMetadata) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

func (x *TokenMetadata) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *TokenMetadata) GetGeneration() int32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type GetCurrentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module requesting the token
	Module string `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	// Instance ID from registration
	InstanceId    string `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentRequest) Reset() {
	*x = GetCurrentRequest{}
	mi := &file_core_internal_token_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentRequest) ProtoMessage() {}

func (x *GetCurrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_internal_token_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentRequest) Descriptor() ([]byte, []int) {
	return file_core_internal_token_proto_rawDescGZIP(), []int{3}
}

func (x *GetCurrentRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *GetCurrentRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type GetCurrentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current valid token
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Token metadata
	Metadata      *TokenMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentResponse) Reset() {
	*x = GetCurrentResponse{}
	mi := &file_core_internal_token_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentResponse) ProtoMessage() {}

func (x *GetCurrentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_internal_token_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentResponse) Descriptor() ([]byte, []int) {
	return file_core_internal_token_proto_rawDescGZIP(), []int{4}
}

func (x *GetCurrentResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetCurrentResponse) GetMetadata() *TokenMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SubscribeRotationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module subscribing to rotation events
	Module string `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	// Instance ID
	InstanceId    string `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRotationRequest) Reset() {
	*x = SubscribeRotationRequest{}
	mi := &file_core_internal_token_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRotationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRotationRequest) ProtoMessage() {}

func (x *SubscribeRotationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_internal_token_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRotationRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRotationRequest) Descriptor() ([]byte, []int) {
	return file_core_internal_token_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeRotationRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *SubscribeRotationRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type TokenRotationEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New token
	NewToken string `protobuf:"bytes,1,opt,name=new_token,json=newToken,proto3" json:"new_token,omitempty"`
	// When the old token expires (grace period)
	OldTokenExpiresAt int64 `protobuf:"varint,2,opt,name=old_token_expires_at,json=oldTokenExpiresAt,proto3" json:"old_token_expires_at,omitempty"`
	// Token metadata
	Metadata      *TokenMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRotationEvent) Reset() {
	*x = TokenRotationEvent{}
	mi := &file_core_internal_token_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRotationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRotationEvent) ProtoMessage() {}

func (x *TokenRotationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_core_internal_token_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRotationEvent.ProtoReflect.Descriptor instead.
func (*TokenRotationEvent) Descriptor() ([]byte, []int) {
	return file_core_internal_token_proto_rawDescGZIP(), []int{6}
}

func (x *TokenRotationEvent) GetNewToken() string {
	if x != nil {
		return x.NewToken
	}
	return ""
}

func (x *TokenRotationEvent) GetOldTokenExpiresAt() int64 {
	if x != nil {
		return x.OldTokenExpiresAt
	}
	return 0
}

func (x *TokenRotationEvent) GetMetadata() *TokenMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_core_internal_token_proto protoreflect.FileDescriptor

const file_core_internal_token_proto_rawDesc = "" +
	"\n" +
	"\x19core/internal_token.proto\x12\x1aaegion.core.internal_token\"?\n" +
	"\x0fValidateRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06module\x18\x02 \x01(\tR\x06module\"\xb3\x01\n" +
	"\x10ValidateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12E\n" +
	"\bmetadata\x18\x04 \x01(\v2).aegion.core.internal_token.TokenMetadataR\bmetadata\"k\n" +
	"\rTokenMetadata\x12\x1b\n" +
	"\tissued_at\x18\x01 \x01(\x03R\bissuedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x05R\n" +
	"generation\"L\n" +
	"\x11GetCurrentRequest\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\"q\n" +
	"\x12GetCurrentResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12E\n" +
	"\bmetadata\x18\x02 \x01(\v2).aegion.core.internal_token.TokenMetadataR\bmetadata\"S\n" +
	"\x18SubscribeRotationRequest\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\"\xa9\x01\n" +
	"\x12TokenRotationEvent\x12\x1b\n" +
	"\tnew_token\x18\x01 \x01(\tR\bnewToken\x12/\n" +
	"\x14old_token_expires_at\x18\x02 \x01(\x03R\x11oldTokenExpiresAt\x12E\n" +
	"\bmetadata\x18\x03 \x01(\v2).aegion.core.internal_token.TokenMetadataR\bmetadata2\xe7\x02\n" +
	"\x14InternalTokenService\x12e\n" +
	"\bValidate\x12+.aegion.core.internal_token.ValidateRequest\x1a,.aegion.core.internal_token.ValidateResponse\x12k\n" +
	"\n" +
	"GetCurrent\x12-.aegion.core.internal_token.GetCurrentRequest\x1a..aegion.core.internal_token.GetCurrentResponse\x12{\n" +
	"\x11SubscribeRotation\x124.aegion.core.internal_token.SubscribeRotationRequest\x1a..aegion.core.internal_token.TokenRotationEvent0\x01B.Z,github.com/aegion/aegion/internal/proto/coreb\x06proto3"

var (
	file_core_internal_token_proto_rawDescOnce sync.Once
	file_core_internal_token_proto_rawDescData []byte
)

func file_core_internal_token_proto_rawDescGZIP() []byte {
	file_core_internal_token_proto_rawDescOnce.Do(func() {
		file_core_internal_token_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_internal_token_proto_rawDesc), len(file_core_internal_token_proto_rawDesc)))
	})
	return file_core_internal_token_proto_rawDescData
}

var file_core_internal_token_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_core_internal_token_proto_goTypes = []any{
	(*ValidateRequest)(nil),          // 0: aegion.core.internal_token.ValidateRequest
	(*ValidateResponse)(nil),         // 1: aegion.core.internal_token.ValidateResponse
	(*TokenMetadata)(nil),            // 2: aegion.core.internal_token.TokenMetadata
	(*GetCurrentRequest)(nil),        // 3: aegion.core.internal_token.GetCurrentRequest
	(*GetCurrentResponse)(nil),       // 4: aegion.core.internal_token.GetCurrentResponse
	(*SubscribeRotationRequest)(nil), // 5: aegion.core.internal_token.SubscribeRotationRequest
	(*TokenRotationEvent)(nil),       // 6: aegion.core.internal_token.TokenRotationEvent
}
var file_core_internal_token_proto_depIdxs = []int32{
	2, // 0: aegion.core.internal_token.ValidateResponse.metadata:type_name -> aegion.core.internal_token.TokenMetadata
	2, // 1: aegion.core.internal_token.GetCurrentResponse.metadata:type_name -> aegion.core.internal_token.TokenMetadata
	2, // 2: aegion.core.internal_token.TokenRotationEvent.metadata:type_name -> aegion.core.internal_token.TokenMetadata
	0, // 3: aegion.core.internal_token.InternalTokenService.Validate:input_type -> aegion.core.internal_token.ValidateRequest
	3, // 4: aegion.core.internal_token.InternalTokenService.GetCurrent:input_type -> aegion.core.internal_token.GetCurrentRequest
	5, // 5: aegion.core.internal_token.InternalTokenService.SubscribeRotation:input_type -> aegion.core.internal_token.SubscribeRotationRequest
	1, // 6: aegion.core.internal_token.InternalTokenService.Validate:output_type -> aegion.core.internal_token.ValidateResponse
	4, // 7: aegion.core.internal_token.InternalTokenService.GetCurrent:output_type -> aegion.core.internal_token.GetCurrentResponse
	6, // 8: aegion.core.internal_token.InternalTokenService.SubscribeRotation:output_type -> aegion.core.internal_token.TokenRotationEvent
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_core_internal_token_proto_init() }
func file_core_internal_token_proto_init() {
	if File_core_internal_token_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_internal_token_proto_rawDesc), len(file_core_internal_token_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_internal_token_proto_goTypes,
		DependencyIndexes: file_core_internal_token_proto_depIdxs,
		MessageInfos:      file_core_internal_token_proto_msgTypes,
	}.Build()
	File_core_internal_token_proto = out.File
	file_core_internal_token_proto_goTypes = nil
	file_core_internal_token_proto_depIdxs = nil
}
