// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: core/internal_token.proto

package core

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InternalTokenService_Validate_FullMethodName          = "/aegion.core.internal_token.InternalTokenService/Validate"
	InternalTokenService_GetCurrent_FullMethodName        = "/aegion.core.internal_token.InternalTokenService/GetCurrent"
	InternalTokenService_SubscribeRotation_FullMethodName = "/aegion.core.internal_token.InternalTokenService/SubscribeRotation"
)

// InternalTokenServiceClient is the client API for InternalTokenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InternalTokenService manages internal authentication tokens.
// Core uses these to authenticate module-to-module calls.
type InternalTokenServiceClient interface {
	// Validate an internal auth token
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
	// Get current token (for modules to retrieve on startup)
	GetCurrent(ctx context.Context, in *GetCurrentRequest, opts ...grpc.CallOption) (*GetCurrentResponse, error)
	// Subscribe to token rotation events
	SubscribeRotation(ctx context.Context, in *SubscribeRotationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TokenRotationEvent], error)
}

type internalTokenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalTokenServiceClient(cc grpc.ClientConnInterface) InternalTokenServiceClient {
	return &internalTokenServiceClient{cc}
}

func (c *internalTokenServiceClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, InternalTokenService_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalTokenServiceClient) GetCurrent(ctx context.Context, in *GetCurrentRequest, opts ...grpc.CallOption) (*GetCurrentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentResponse)
	err := c.cc.Invoke(ctx, InternalTokenService_GetCurrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalTokenServiceClient) SubscribeRotation(ctx context.Context, in *SubscribeRotationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TokenRotationEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InternalTokenService_ServiceDesc.Streams[0], InternalTokenService_SubscribeRotation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRotationRequest, TokenRotationEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InternalTokenService_SubscribeRotationClient = grpc.ServerStreamingClient[TokenRotationEvent]

// InternalTokenServiceServer is the server API for InternalTokenService service.
// All implementations must embed UnimplementedInternalTokenServiceServer
// for forward compatibility.
//
// InternalTokenService manages internal authentication tokens.
// Core uses these to authenticate module-to-module calls.
type InternalTokenServiceServer interface {
	// Validate an internal auth token
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
	// Get current token (for modules to retrieve on startup)
	GetCurrent(context.Context, *GetCurrentRequest) (*GetCurrentResponse, error)
	// Subscribe to token rotation events
	SubscribeRotation(*SubscribeRotationRequest, grpc.ServerStreamingServer[TokenRotationEvent]) error
	mustEmbedUnimplementedInternalTokenServiceServer()
}

// UnimplementedInternalTokenServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalTokenServiceServer struct{}

func (UnimplementedInternalTokenServiceServer) Validate(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedInternalTokenServiceServer) GetCurrent(context.Context, *GetCurrentRequest) (*GetCurrentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrent not implemented")
}
func (UnimplementedInternalTokenServiceServer) SubscribeRotation(*SubscribeRotationRequest, grpc.ServerStreamingServer[TokenRotationEvent]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeRotation not implemented")
}
func (UnimplementedInternalTokenServiceServer) mustEmbedUnimplementedInternalTokenServiceServer() {}
func (UnimplementedInternalTokenServiceServer) testEmbeddedByValue()                              {}

// UnsafeInternalTokenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalTokenServiceServer will
// result in compilation errors.
type UnsafeInternalTokenServiceServer interface {
	mustEmbedUnimplementedInternalTokenServiceServer()
}

func RegisterInternalTokenServiceServer(s grpc.ServiceRegistrar, srv InternalTokenServiceServer) {
	// If the following call pancis, it indicates UnimplementedInternalTokenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalTokenService_ServiceDesc, srv)
}

func _InternalTokenService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalTokenServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalTokenService_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalTokenServiceServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalTokenService_GetCurrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalTokenServiceServer).GetCurrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalTokenService_GetCurrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalTokenServiceServer).GetCurrent(ctx, req.(*GetCurrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalTokenService_SubscribeRotation_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRotationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InternalTokenServiceServer).SubscribeRotation(m, &grpc.GenericServerStream[SubscribeRotationRequest, TokenRotationEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InternalTokenService_SubscribeRotationServer = grpc.ServerStreamingServer[TokenRotationEvent]

// InternalTokenService_ServiceDesc is the grpc.ServiceDesc for InternalTokenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalTokenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aegion.core.internal_token.InternalTokenService",
	HandlerType: (*InternalTokenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _InternalTokenService_Validate_Handler,
		},
		{
			MethodName: "GetCurrent",
			Handler:    _InternalTokenService_GetCurrent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeRotation",
			Handler:       _InternalTokenService_SubscribeRotation_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "core/internal_token.proto",
}
