// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: core/registry.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNKNOWN   HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY   HealthStatus = 1
	HealthStatus_HEALTH_STATUS_DEGRADED  HealthStatus = 2
	HealthStatus_HEALTH_STATUS_UNHEALTHY HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNKNOWN",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_DEGRADED",
		3: "HEALTH_STATUS_UNHEALTHY",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNKNOWN":   0,
		"HEALTH_STATUS_HEALTHY":   1,
		"HEALTH_STATUS_DEGRADED":  2,
		"HEALTH_STATUS_UNHEALTHY": 3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_core_registry_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_core_registry_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_core_registry_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module name (e.g., "password", "mfa", "oauth2")
	Module string `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	// Semantic version (e.g., "2.1.0")
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Internal network address (e.g., "aegion-mfa-1:9002")
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	// HTTP routes this module handles (e.g., ["/self-service/mfa/*"])
	Routes []string `protobuf:"bytes,4,rep,name=routes,proto3" json:"routes,omitempty"`
	// Capabilities this module provides (e.g., ["totp", "webauthn"])
	Capabilities []string `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Health check URL
	HealthUrl string `protobuf:"bytes,6,opt,name=health_url,json=healthUrl,proto3" json:"health_url,omitempty"`
	// Ready check URL
	ReadyUrl string `protobuf:"bytes,7,opt,name=ready_url,json=readyUrl,proto3" json:"ready_url,omitempty"`
	// gRPC services this module exposes
	GrpcServices []string `protobuf:"bytes,8,rep,name=grpc_services,json=grpcServices,proto3" json:"grpc_services,omitempty"`
	// Events this module subscribes to
	EventSubscriptions []string `protobuf:"bytes,9,rep,name=event_subscriptions,json=eventSubscriptions,proto3" json:"event_subscriptions,omitempty"`
	// Bootstrap credential issued out-of-band by core; required for registration.
	BootstrapSecret string `protobuf:"bytes,10,opt,name=bootstrap_secret,json=bootstrapSecret,proto3" json:"bootstrap_secret,omitempty"`
	// Private HTTP listener address registered for core-owned public routing.
	// It MUST be reachable only on the module network.
	HttpAddress   string `protobuf:"bytes,11,opt,name=http_address,json=httpAddress,proto3" json:"http_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_core_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_core_registry_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterRequest) GetRoutes() []string {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetHealthUrl() string {
	if x != nil {
		return x.HealthUrl
	}
	return ""
}

func (x *RegisterRequest) GetReadyUrl() string {
	if x != nil {
		return x.ReadyUrl
	}
	return ""
}

func (x *RegisterRequest) GetGrpcServices() []string {
	if x != nil {
		return x.GrpcServices
	}
	return nil
}

func (x *RegisterRequest) GetEventSubscriptions() []string {
	if x != nil {
		return x.EventSubscriptions
	}
	return nil
}

func (x *RegisterRequest) GetBootstrapSecret() string {
	if x != nil {
		return x.BootstrapSecret
	}
	return ""
}

func (x *RegisterRequest) GetHttpAddress() string {
	if x != nil {
		return x.HttpAddress
	}
	return ""
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique instance ID assigned by core
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// Success status
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if registration failed
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_core_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_core_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeregisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instance ID from registration
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// Module name
	Module string `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	// Reason for deregistration
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_core_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_core_registry_proto_rawDescGZIP(), []int{2}
}

func (x *DeregisterRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DeregisterRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *DeregisterRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_core_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_core_registry_proto_rawDescGZIP(), []int{3}
}

func (x *DeregisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Instance ID from registration
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// Module name
	Module string `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	// Current health status
	Status HealthStatus `protobuf:"varint,3,opt,name=status,proto3,enum=aegion.core.registry.HealthStatus" json:"status,omitempty"`
	// Optional metrics
	Metrics       *ModuleMetrics `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_core_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_core_registry_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HeartbeatRequest) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNKNOWN
}

func (x *HeartbeatRequest) GetMetrics() *ModuleMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the heartbeat was accepted
	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// If false, module should re-register
	ShouldReregister bool `protobuf:"varint,2,opt,name=should_reregister,json=shouldReregister,proto3" json:"should_reregister,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_core_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_core_registry_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HeartbeatResponse) GetShouldReregister() bool {
	if x != nil {
		return x.ShouldReregister
	}
	return false
}

type GetModulesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter by module name
	ModuleFilter string `protobuf:"bytes,1,opt,name=module_filter,json=moduleFilter,proto3" json:"module_filter,omitempty"`
	// Include unhealthy instances
	IncludeUnhealthy bool `protobuf:"varint,2,opt,name=include_unhealthy,json=includeUnhealthy,proto3" json:"include_unhealthy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetModulesRequest) Reset() {
	*x = GetModulesRequest{}
	mi := &file_core_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModulesRequest) ProtoMessage() {}

func (x *GetModulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModulesRequest.ProtoReflect.Descriptor instead.
func (*GetModulesRequest) Descriptor() ([]byte, []int) {
	return file_core_registry_proto_rawDescGZIP(), []int{6}
}

func (x *GetModulesRequest) GetModuleFilter() string {
	if x != nil {
		return x.ModuleFilter
	}
	return ""
}

func (x *GetModulesRequest) GetIncludeUnhealthy() bool {
	if x != nil {
		return x.IncludeUnhealthy
	}
	return false
}

type GetModulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modules       []*ModuleInstance      `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModulesResponse) Reset() {
	*x = GetModulesResponse{}
	mi := &file_core_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModulesResponse) ProtoMessage() {}

func (x *GetModulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModulesResponse.ProtoReflect.Descriptor instead.
func (*GetModulesResponse) Descriptor() ([]byte, []int) {
	return file_core_registry_proto_rawDescGZIP(), []int{7}
}

func (x *GetModulesResponse) GetModules() []*ModuleInstance {
	if x != nil {
		return x.Modules
	}
	return nil
}

type ModuleInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Module        string                 `protobuf:"bytes,2,opt,name=module,proto3" json:"module,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Routes        []string               `protobuf:"bytes,5,rep,name=routes,proto3" json:"routes,omitempty"`
	Capabilities  []string               `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Status        HealthStatus           `protobuf:"varint,7,opt,name=status,proto3,enum=aegion.core.registry.HealthStatus" json:"status,omitempty"`
	RegisteredAt  int64                  `protobuf:"varint,8,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	LastHeartbeat int64                  `protobuf:"varint,9,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleInstance) Reset() {
	*x = ModuleInstance{}
	mi := &file_core_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleInstance) ProtoMessage() {}

func (x *ModuleInstance) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleInstance.ProtoReflect.Descriptor instead.
func (*ModuleInstance) Descriptor() ([]byte, []int) {
	return file_core_registry_proto_rawDescGZIP(), []int{8}
}

func (x *ModuleInstance) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ModuleInstance) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *ModuleInstance) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModuleInstance) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ModuleInstance) GetRoutes() []string {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *ModuleInstance) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ModuleInstance) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNKNOWN
}

func (x *ModuleInstance) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

func (x *ModuleInstance) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

type ModuleMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Requests handled since last heartbeat
	RequestsHandled int64 `protobuf:"varint,1,opt,name=requests_handled,json=requestsHandled,proto3" json:"requests_handled,omitempty"`
	// Current active connections
	ActiveConnections int32 `protobuf:"varint,2,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	// Average response time in milliseconds
	AvgResponseMs float64 `protobuf:"fixed64,3,opt,name=avg_response_ms,json=avgResponseMs,proto3" json:"avg_response_ms,omitempty"`
	// Error count since last heartbeat
	ErrorCount    int64 `protobuf:"varint,4,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleMetrics) Reset() {
	*x = ModuleMetrics{}
	mi := &file_core_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleMetrics) ProtoMessage() {}

func (x *ModuleMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_core_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleMetrics.ProtoReflect.Descriptor instead.
func (*ModuleMetrics) Descriptor() ([]byte, []int) {
	return file_core_registry_proto_rawDescGZIP(), []int{9}
}

func (x *ModuleMetrics) GetRequestsHandled() int64 {
	if x != nil {
		return x.RequestsHandled
	}
	return 0
}

func (x *ModuleMetrics) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *ModuleMetrics) GetAvgResponseMs() float64 {
	if x != nil {
		return x.AvgResponseMs
	}
	return 0
}

func (x *ModuleMetrics) GetErrorCount() int64 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

var File_core_registry_proto protoreflect.FileDescriptor

const file_core_registry_proto_rawDesc = "" +
	"\n" +
	"\x13core/registry.proto\x12\x14aegion.core.registry\"\xf9\x02\n" +
	"\x0fRegisterRequest\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x16\n" +
	"\x06routes\x18\x04 \x03(\tR\x06routes\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x12\x1d\n" +
	"\n" +
	"health_url\x18\x06 \x01(\tR\thealthUrl\x12\x1b\n" +
	"\tready_url\x18\a \x01(\tR\breadyUrl\x12#\n" +
	"\rgrpc_services\x18\b \x03(\tR\fgrpcServices\x12/\n" +
	"\x13event_subscriptions\x18\t \x03(\tR\x12eventSubscriptions\x12)\n" +
	"\x10bootstrap_secret\x18\n" +
	" \x01(\tR\x0fbootstrapSecret\x12!\n" +
	"\fhttp_address\x18\v \x01(\tR\vhttpAddress\"c\n" +
	"\x10RegisterResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"d\n" +
	"\x11DeregisterRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06module\x18\x02 \x01(\tR\x06module\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\".\n" +
	"\x12DeregisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xc6\x01\n" +
	"\x10HeartbeatRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06module\x18\x02 \x01(\tR\x06module\x12:\n" +
	"\x06status\x18\x03 \x01(\x0e2\".aegion.core.registry.HealthStatusR\x06status\x12=\n" +
	"\ametrics\x18\x04 \x01(\v2#.aegion.core.registry.ModuleMetricsR\ametrics\"\\\n" +
	"\x11HeartbeatResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12+\n" +
	"\x11should_reregister\x18\x02 \x01(\bR\x10shouldReregister\"e\n" +
	"\x11GetModulesRequest\x12#\n" +
	"\rmodule_filter\x18\x01 \x01(\tR\fmoduleFilter\x12+\n" +
	"\x11include_unhealthy\x18\x02 \x01(\bR\x10includeUnhealthy\"T\n" +
	"\x12GetModulesResponse\x12>\n" +
	"\amodules\x18\x01 \x03(\v2$.aegion.core.registry.ModuleInstanceR\amodules\"\xc1\x02\n" +
	"\x0eModuleInstance\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06module\x18\x02 \x01(\tR\x06module\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x16\n" +
	"\x06routes\x18\x05 \x03(\tR\x06routes\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x12:\n" +
	"\x06status\x18\a \x01(\x0e2\".aegion.core.registry.HealthStatusR\x06status\x12#\n" +
	"\rregistered_at\x18\b \x01(\x03R\fregisteredAt\x12%\n" +
	"\x0elast_heartbeat\x18\t \x01(\x03R\rlastHeartbeat\"\xb2\x01\n" +
	"\rModuleMetrics\x12)\n" +
	"\x10requests_handled\x18\x01 \x01(\x03R\x0frequestsHandled\x12-\n" +
	"\x12active_connections\x18\x02 \x01(\x05R\x11activeConnections\x12&\n" +
	"\x0favg_response_ms\x18\x03 \x01(\x01R\ravgResponseMs\x12\x1f\n" +
	"\verror_count\x18\x04 \x01(\x03R\n" +
	"errorCount*}\n" +
	"\fHealthStatus\x12\x19\n" +
	"\x15HEALTH_STATUS_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x02\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x032\x8b\x03\n" +
	"\x0eModuleRegistry\x12Y\n" +
	"\bRegister\x12%.aegion.core.registry.RegisterRequest\x1a&.aegion.core.registry.RegisterResponse\x12_\n" +
	"\n" +
	"Deregister\x12'.aegion.core.registry.DeregisterRequest\x1a(.aegion.core.registry.DeregisterResponse\x12\\\n" +
	"\tHeartbeat\x12&.aegion.core.registry.HeartbeatRequest\x1a'.aegion.core.registry.HeartbeatResponse\x12_\n" +
	"\n" +
	"GetModules\x12'.aegion.core.registry.GetModulesRequest\x1a(.aegion.core.registry.GetModulesResponseB.Z,github.com/aegion/aegion/internal/proto/coreb\x06proto3"

var (
	file_core_registry_proto_rawDescOnce sync.Once
	file_core_registry_proto_rawDescData []byte
)

func file_core_registry_proto_rawDescGZIP() []byte {
	file_core_registry_proto_rawDescOnce.Do(func() {
		file_core_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_registry_proto_rawDesc), len(file_core_registry_proto_rawDesc)))
	})
	return file_core_registry_proto_rawDescData
}

var file_core_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_core_registry_proto_goTypes = []any{
	(HealthStatus)(0),          // 0: aegion.core.registry.HealthStatus
	(*RegisterRequest)(nil),    // 1: aegion.core.registry.RegisterRequest
	(*RegisterResponse)(nil),   // 2: aegion.core.registry.RegisterResponse
	(*DeregisterRequest)(nil),  // 3: aegion.core.registry.DeregisterRequest
	(*DeregisterResponse)(nil), // 4: aegion.core.registry.DeregisterResponse
	(*HeartbeatRequest)(nil),   // 5: aegion.core.registry.HeartbeatRequest
	(*HeartbeatResponse)(nil),  // 6: aegion.core.registry.HeartbeatResponse
	(*GetModulesRequest)(nil),  // 7: aegion.core.registry.GetModulesRequest
	(*GetModulesResponse)(nil), // 8: aegion.core.registry.GetModulesResponse
	(*ModuleInstance)(nil),     // 9: aegion.core.registry.ModuleInstance
	(*ModuleMetrics)(nil),      // 10: aegion.core.registry.ModuleMetrics
}
var file_core_registry_proto_depIdxs = []int32{
	0,  // 0: aegion.core.registry.HeartbeatRequest.status:type_name -> aegion.core.registry.HealthStatus
	10, // 1: aegion.core.registry.HeartbeatRequest.metrics:type_name -> aegion.core.registry.ModuleMetrics
	9,  // 2: aegion.core.registry.GetModulesResponse.modules:type_name -> aegion.core.registry.ModuleInstance
	0,  // 3: aegion.core.registry.ModuleInstance.status:type_name -> aegion.core.registry.HealthStatus
	1,  // 4: aegion.core.registry.ModuleRegistry.Register:input_type -> aegion.core.registry.RegisterRequest
	3,  // 5: aegion.core.registry.ModuleRegistry.Deregister:input_type -> aegion.core.registry.DeregisterRequest
	5,  // 6: aegion.core.registry.ModuleRegistry.Heartbeat:input_type -> aegion.core.registry.HeartbeatRequest
	7,  // 7: aegion.core.registry.ModuleRegistry.GetModules:input_type -> aegion.core.registry.GetModulesRequest
	2,  // 8: aegion.core.registry.ModuleRegistry.Register:output_type -> aegion.core.registry.RegisterResponse
	4,  // 9: aegion.core.registry.ModuleRegistry.Deregister:output_type -> aegion.core.registry.DeregisterResponse
	6,  // 10: aegion.core.registry.ModuleRegistry.Heartbeat:output_type -> aegion.core.registry.HeartbeatResponse
	8,  // 11: aegion.core.registry.ModuleRegistry.GetModules:output_type -> aegion.core.registry.GetModulesResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_core_registry_proto_init() }
func file_core_registry_proto_init() {
	if File_core_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_registry_proto_rawDesc), len(file_core_registry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_registry_proto_goTypes,
		DependencyIndexes: file_core_registry_proto_depIdxs,
		EnumInfos:         file_core_registry_proto_enumTypes,
		MessageInfos:      file_core_registry_proto_msgTypes,
	}.Build()
	File_core_registry_proto = out.File
	file_core_registry_proto_goTypes = nil
	file_core_registry_proto_depIdxs = nil
}
