// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: core/registry.proto

package core

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModuleRegistry_Register_FullMethodName   = "/aegion.core.registry.ModuleRegistry/Register"
	ModuleRegistry_Deregister_FullMethodName = "/aegion.core.registry.ModuleRegistry/Deregister"
	ModuleRegistry_Heartbeat_FullMethodName  = "/aegion.core.registry.ModuleRegistry/Heartbeat"
	ModuleRegistry_GetModules_FullMethodName = "/aegion.core.registry.ModuleRegistry/GetModules"
)

// ModuleRegistryClient is the client API for ModuleRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ModuleRegistry is the service that modules use to register themselves with core.
// Core maintains the service registry and routes requests to registered modules.
type ModuleRegistryClient interface {
	// Register a module instance with core
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Deregister a module instance (graceful shutdown)
	Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error)
	// Heartbeat to maintain registration (called every 5s by modules)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// GetModules returns all registered module instances (admin use)
	GetModules(ctx context.Context, in *GetModulesRequest, opts ...grpc.CallOption) (*GetModulesResponse, error)
}

type moduleRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewModuleRegistryClient(cc grpc.ClientConnInterface) ModuleRegistryClient {
	return &moduleRegistryClient{cc}
}

func (c *moduleRegistryClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, ModuleRegistry_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleRegistryClient) Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeregisterResponse)
	err := c.cc.Invoke(ctx, ModuleRegistry_Deregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleRegistryClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ModuleRegistry_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleRegistryClient) GetModules(ctx context.Context, in *GetModulesRequest, opts ...grpc.CallOption) (*GetModulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModulesResponse)
	err := c.cc.Invoke(ctx, ModuleRegistry_GetModules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModuleRegistryServer is the server API for ModuleRegistry service.
// All implementations must embed UnimplementedModuleRegistryServer
// for forward compatibility.
//
// ModuleRegistry is the service that modules use to register themselves with core.
// Core maintains the service registry and routes requests to registered modules.
type ModuleRegistryServer interface {
	// Register a module instance with core
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Deregister a module instance (graceful shutdown)
	Deregister(context.Context, *DeregisterRequest) (*DeregisterResponse, error)
	// Heartbeat to maintain registration (called every 5s by modules)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// GetModules returns all registered module instances (admin use)
	GetModules(context.Context, *GetModulesRequest) (*GetModulesResponse, error)
	mustEmbedUnimplementedModuleRegistryServer()
}

// UnimplementedModuleRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModuleRegistryServer struct{}

func (UnimplementedModuleRegistryServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedModuleRegistryServer) Deregister(context.Context, *DeregisterRequest) (*DeregisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deregister not implemented")
}
func (UnimplementedModuleRegistryServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedModuleRegistryServer) GetModules(context.Context, *GetModulesRequest) (*GetModulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModules not implemented")
}
func (UnimplementedModuleRegistryServer) mustEmbedUnimplementedModuleRegistryServer() {}
func (UnimplementedModuleRegistryServer) testEmbeddedByValue()                        {}

// UnsafeModuleRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModuleRegistryServer will
// result in compilation errors.
type UnsafeModuleRegistryServer interface {
	mustEmbedUnimplementedModuleRegistryServer()
}

func RegisterModuleRegistryServer(s grpc.ServiceRegistrar, srv ModuleRegistryServer) {
	// If the following call pancis, it indicates UnimplementedModuleRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModuleRegistry_ServiceDesc, srv)
}

func _ModuleRegistry_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleRegistryServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleRegistry_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleRegistryServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleRegistry_Deregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleRegistryServer).Deregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleRegistry_Deregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleRegistryServer).Deregister(ctx, req.(*DeregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleRegistry_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleRegistryServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleRegistry_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleRegistryServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleRegistry_GetModules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleRegistryServer).GetModules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleRegistry_GetModules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleRegistryServer).GetModules(ctx, req.(*GetModulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModuleRegistry_ServiceDesc is the grpc.ServiceDesc for ModuleRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModuleRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aegion.core.registry.ModuleRegistry",
	HandlerType: (*ModuleRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _ModuleRegistry_Register_Handler,
		},
		{
			MethodName: "Deregister",
			Handler:    _ModuleRegistry_Deregister_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ModuleRegistry_Heartbeat_Handler,
		},
		{
			MethodName: "GetModules",
			Handler:    _ModuleRegistry_GetModules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core/registry.proto",
}
