// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.3
// source: core/session.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session token (from cookie or header)
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Required minimum AAL (optional)
	RequiredAal   string `protobuf:"bytes,2,opt,name=required_aal,json=requiredAal,proto3" json:"required_aal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_core_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_core_session_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResolveRequest) GetRequiredAal() string {
	if x != nil {
		return x.RequiredAal
	}
	return ""
}

type ResolveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the session is valid
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// Session context if valid
	Session *SessionContext `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	// Error code if invalid
	ErrorCode string `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// Human-readable error message
	ErrorMessage  string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_core_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_core_session_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ResolveResponse) GetSession() *SessionContext {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *ResolveResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ResolveResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SessionContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Identity ID
	IdentityId string `protobuf:"bytes,2,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	// Current Authentication Assurance Level
	Aal string `protobuf:"bytes,3,opt,name=aal,proto3" json:"aal,omitempty"`
	// Authentication methods used in this session
	AuthMethods []*AuthMethod `protobuf:"bytes,4,rep,name=auth_methods,json=authMethods,proto3" json:"auth_methods,omitempty"`
	// Session issue timestamp
	IssuedAt int64 `protobuf:"varint,5,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	// Session expiry timestamp
	ExpiresAt int64 `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Last authentication timestamp
	AuthenticatedAt int64 `protobuf:"varint,7,opt,name=authenticated_at,json=authenticatedAt,proto3" json:"authenticated_at,omitempty"`
	// Identity traits (email, name, etc.)
	Traits map[string]string `protobuf:"bytes,8,rep,name=traits,proto3" json:"traits,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Identity metadata (public)
	Metadata map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Whether this is an impersonation session
	IsImpersonation bool `protobuf:"varint,10,opt,name=is_impersonation,json=isImpersonation,proto3" json:"is_impersonation,omitempty"`
	// Original admin identity ID if impersonation
	ImpersonatorId string `protobuf:"bytes,11,opt,name=impersonator_id,json=impersonatorId,proto3" json:"impersonator_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionContext) Reset() {
	*x = SessionContext{}
	mi := &file_core_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionContext) ProtoMessage() {}

func (x *SessionContext) ProtoReflect() protoreflect.Message {
	mi := &file_core_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionContext.ProtoReflect.Descriptor instead.
func (*SessionContext) Descriptor() ([]byte, []int) {
	return file_core_session_proto_rawDescGZIP(), []int{2}
}

func (x *SessionContext) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionContext) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *SessionContext) GetAal() string {
	if x != nil {
		return x.Aal
	}
	return ""
}

func (x *SessionContext) GetAuthMethods() []*AuthMethod {
	if x != nil {
		return x.AuthMethods
	}
	return nil
}

func (x *SessionContext) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

func (x *SessionContext) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *SessionContext) GetAuthenticatedAt() int64 {
	if x != nil {
		return x.AuthenticatedAt
	}
	return 0
}

func (x *SessionContext) GetTraits() map[string]string {
	if x != nil {
		return x.Traits
	}
	return nil
}

func (x *SessionContext) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SessionContext) GetIsImpersonation() bool {
	if x != nil {
		return x.IsImpersonation
	}
	return false
}

func (x *SessionContext) GetImpersonatorId() string {
	if x != nil {
		return x.ImpersonatorId
	}
	return ""
}

type AuthMethod struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Method type (password, totp, webauthn, etc.)
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// AAL contributed by this method
	AalContributed string `protobuf:"bytes,2,opt,name=aal_contributed,json=aalContributed,proto3" json:"aal_contributed,omitempty"`
	// When this method was completed
	CompletedAt   int64 `protobuf:"varint,3,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthMethod) Reset() {
	*x = AuthMethod{}
	mi := &file_core_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthMethod) ProtoMessage() {}

func (x *AuthMethod) ProtoReflect() protoreflect.Message {
	mi := &file_core_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthMethod.ProtoReflect.Descriptor instead.
func (*AuthMethod) Descriptor() ([]byte, []int) {
	return file_core_session_proto_rawDescGZIP(), []int{3}
}

func (x *AuthMethod) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AuthMethod) GetAalContributed() string {
	if x != nil {
		return x.AalContributed
	}
	return ""
}

func (x *AuthMethod) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

type CreateSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity ID to create session for
	IdentityId string `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	// Initial authentication method
	AuthMethod string `protobuf:"bytes,2,opt,name=auth_method,json=authMethod,proto3" json:"auth_method,omitempty"`
	// Initial AAL
	Aal string `protobuf:"bytes,3,opt,name=aal,proto3" json:"aal,omitempty"`
	// Device info
	Device *DeviceInfo `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	// Session lifetime in seconds (0 = use default)
	LifetimeSeconds int64 `protobuf:"varint,5,opt,name=lifetime_seconds,json=lifetimeSeconds,proto3" json:"lifetime_seconds,omitempty"`
	// Whether this is an impersonation session
	IsImpersonation bool `protobuf:"varint,6,opt,name=is_impersonation,json=isImpersonation,proto3" json:"is_impersonation,omitempty"`
	// Admin identity ID if impersonation
	ImpersonatorId string `protobuf:"bytes,7,opt,name=impersonator_id,json=impersonatorId,proto3" json:"impersonator_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_core_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_core_session_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSessionRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *CreateSessionRequest) GetAuthMethod() string {
	if x != nil {
		return x.AuthMethod
	}
	return ""
}

func (x *CreateSessionRequest) GetAal() string {
	if x != nil {
		return x.Aal
	}
	return ""
}

func (x *CreateSessionRequest) GetDevice() *DeviceInfo {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *CreateSessionRequest) GetLifetimeSeconds() int64 {
	if x != nil {
		return x.LifetimeSeconds
	}
	return 0
}

func (x *CreateSessionRequest) GetIsImpersonation() bool {
	if x != nil {
		return x.IsImpersonation
	}
	return false
}

func (x *CreateSessionRequest) GetImpersonatorId() string {
	if x != nil {
		return x.ImpersonatorId
	}
	return ""
}

type CreateSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Created session
	Session *SessionContext `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	// Session token to set in cookie
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// CSRF token for this session
	CsrfToken     string `protobuf:"bytes,3,opt,name=csrf_token,json=csrfToken,proto3" json:"csrf_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_core_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_core_session_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSessionResponse) GetSession() *SessionContext {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *CreateSessionResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateSessionResponse) GetCsrfToken() string {
	if x != nil {
		return x.CsrfToken
	}
	return ""
}

type UpdateSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session ID to update
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// New AAL after step-up
	NewAal string `protobuf:"bytes,2,opt,name=new_aal,json=newAal,proto3" json:"new_aal,omitempty"`
	// Auth method that was added
	AddedMethod *AuthMethod `protobuf:"bytes,3,opt,name=added_method,json=addedMethod,proto3" json:"added_method,omitempty"`
	// Updated device info
	Device        *DeviceInfo `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionRequest) Reset() {
	*x = UpdateSessionRequest{}
	mi := &file_core_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionRequest) ProtoMessage() {}

func (x *UpdateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSessionRequest) Descriptor() ([]byte, []int) {
	return file_core_session_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UpdateSessionRequest) GetNewAal() string {
	if x != nil {
		return x.NewAal
	}
	return ""
}

func (x *UpdateSessionRequest) GetAddedMethod() *AuthMethod {
	if x != nil {
		return x.AddedMethod
	}
	return nil
}

func (x *UpdateSessionRequest) GetDevice() *DeviceInfo {
	if x != nil {
		return x.Device
	}
	return nil
}

type UpdateSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Updated session
	Session *SessionContext `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	// Whether update succeeded
	Success       bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionResponse) Reset() {
	*x = UpdateSessionResponse{}
	mi := &file_core_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionResponse) ProtoMessage() {}

func (x *UpdateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionResponse.ProtoReflect.Descriptor instead.
func (*UpdateSessionResponse) Descriptor() ([]byte, []int) {
	return file_core_session_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSessionResponse) GetSession() *SessionContext {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *UpdateSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RevokeSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session ID to revoke
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Reason for revocation
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionRequest) Reset() {
	*x = RevokeSessionRequest{}
	mi := &file_core_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest) ProtoMessage() {}

func (x *RevokeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionRequest.ProtoReflect.Descriptor instead.
func (*RevokeSessionRequest) Descriptor() ([]byte, []int) {
	return file_core_session_proto_rawDescGZIP(), []int{8}
}

func (x *RevokeSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RevokeSessionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RevokeSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionResponse) Reset() {
	*x = RevokeSessionResponse{}
	mi := &file_core_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionResponse) ProtoMessage() {}

func (x *RevokeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionResponse.ProtoReflect.Descriptor instead.
func (*RevokeSessionResponse) Descriptor() ([]byte, []int) {
	return file_core_session_proto_rawDescGZIP(), []int{9}
}

func (x *RevokeSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RevokeAllRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity ID to revoke all sessions for
	IdentityId string `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	// Optionally exclude a specific session (e.g., current session)
	ExcludeSessionId string `protobuf:"bytes,2,opt,name=exclude_session_id,json=excludeSessionId,proto3" json:"exclude_session_id,omitempty"`
	// Reason for revocation
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAllRequest) Reset() {
	*x = RevokeAllRequest{}
	mi := &file_core_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAllRequest) ProtoMessage() {}

func (x *RevokeAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAllRequest.ProtoReflect.Descriptor instead.
func (*RevokeAllRequest) Descriptor() ([]byte, []int) {
	return file_core_session_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeAllRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *RevokeAllRequest) GetExcludeSessionId() string {
	if x != nil {
		return x.ExcludeSessionId
	}
	return ""
}

func (x *RevokeAllRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RevokeAllResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of sessions revoked
	RevokedCount  int32 `protobuf:"varint,1,opt,name=revoked_count,json=revokedCount,proto3" json:"revoked_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAllResponse) Reset() {
	*x = RevokeAllResponse{}
	mi := &file_core_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAllResponse) ProtoMessage() {}

func (x *RevokeAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAllResponse.ProtoReflect.Descriptor instead.
func (*RevokeAllResponse) Descriptor() ([]byte, []int) {
	return file_core_session_proto_rawDescGZIP(), []int{11}
}

func (x *RevokeAllResponse) GetRevokedCount() int32 {
	if x != nil {
		return x.RevokedCount
	}
	return 0
}

type ListSessionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity ID to list sessions for
	IdentityId string `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	// Include revoked/expired sessions
	IncludeInactive bool `protobuf:"varint,2,opt,name=include_inactive,json=includeInactive,proto3" json:"include_inactive,omitempty"`
	// Pagination
	PageSize      int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_core_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_core_session_proto_rawDescGZIP(), []int{12}
}

func (x *ListSessionsRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *ListSessionsRequest) GetIncludeInactive() bool {
	if x != nil {
		return x.IncludeInactive
	}
	return false
}

func (x *ListSessionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSessionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_core_session_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_session_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_core_session_proto_rawDescGZIP(), []int{13}
}

func (x *ListSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type SessionInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Aal             string                 `protobuf:"bytes,2,opt,name=aal,proto3" json:"aal,omitempty"`
	AuthMethods     []*AuthMethod          `protobuf:"bytes,3,rep,name=auth_methods,json=authMethods,proto3" json:"auth_methods,omitempty"`
	IssuedAt        int64                  `protobuf:"varint,4,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt       int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	AuthenticatedAt int64                  `protobuf:"varint,6,opt,name=authenticated_at,json=authenticatedAt,proto3" json:"authenticated_at,omitempty"`
	Active          bool                   `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
	Device          *DeviceInfo            `protobuf:"bytes,8,opt,name=device,proto3" json:"device,omitempty"`
	IsImpersonation bool                   `protobuf:"varint,9,opt,name=is_impersonation,json=isImpersonation,proto3" json:"is_impersonation,omitempty"`
	ImpersonatorId  string                 `protobuf:"bytes,10,opt,name=impersonator_id,json=impersonatorId,proto3" json:"impersonator_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_core_session_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_session_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_core_session_proto_rawDescGZIP(), []int{14}
}

func (x *SessionInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionInfo) GetAal() string {
	if x != nil {
		return x.Aal
	}
	return ""
}

func (x *SessionInfo) GetAuthMethods() []*AuthMethod {
	if x != nil {
		return x.AuthMethods
	}
	return nil
}

func (x *SessionInfo) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

func (x *SessionInfo) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *SessionInfo) GetAuthenticatedAt() int64 {
	if x != nil {
		return x.AuthenticatedAt
	}
	return 0
}

func (x *SessionInfo) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *SessionInfo) GetDevice() *DeviceInfo {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *SessionInfo) GetIsImpersonation() bool {
	if x != nil {
		return x.IsImpersonation
	}
	return false
}

func (x *SessionInfo) GetImpersonatorId() string {
	if x != nil {
		return x.ImpersonatorId
	}
	return ""
}

type DeviceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client IP address
	IpAddress string `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// User agent string
	UserAgent string `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	// Parsed device type
	DeviceType string `protobuf:"bytes,3,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	// Parsed browser
	Browser string `protobuf:"bytes,4,opt,name=browser,proto3" json:"browser,omitempty"`
	// Parsed OS
	Os string `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	// Last seen timestamp
	LastSeenAt int64 `protobuf:"varint,6,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	// Geographic location (if available)
	Location      string `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_core_session_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_session_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_core_session_proto_rawDescGZIP(), []int{15}
}

func (x *DeviceInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *DeviceInfo) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *DeviceInfo) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *DeviceInfo) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *DeviceInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *DeviceInfo) GetLastSeenAt() int64 {
	if x != nil {
		return x.LastSeenAt
	}
	return 0
}

func (x *DeviceInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

var File_core_session_proto protoreflect.FileDescriptor

const file_core_session_proto_rawDesc = "" +
	"\n" +
	"\x12core/session.proto\x12\x13aegion.core.session\"I\n" +
	"\x0eResolveRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12!\n" +
	"\frequired_aal\x18\x02 \x01(\tR\vrequiredAal\"\xaa\x01\n" +
	"\x0fResolveResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12=\n" +
	"\asession\x18\x02 \x01(\v2#.aegion.core.session.SessionContextR\asession\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\xe2\x04\n" +
	"\x0eSessionContext\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\videntity_id\x18\x02 \x01(\tR\n" +
	"identityId\x12\x10\n" +
	"\x03aal\x18\x03 \x01(\tR\x03aal\x12B\n" +
	"\fauth_methods\x18\x04 \x03(\v2\x1f.aegion.core.session.AuthMethodR\vauthMethods\x12\x1b\n" +
	"\tissued_at\x18\x05 \x01(\x03R\bissuedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\x12)\n" +
	"\x10authenticated_at\x18\a \x01(\x03R\x0fauthenticatedAt\x12G\n" +
	"\x06traits\x18\b \x03(\v2/.aegion.core.session.SessionContext.TraitsEntryR\x06traits\x12M\n" +
	"\bmetadata\x18\t \x03(\v21.aegion.core.session.SessionContext.MetadataEntryR\bmetadata\x12)\n" +
	"\x10is_impersonation\x18\n" +
	" \x01(\bR\x0fisImpersonation\x12'\n" +
	"\x0fimpersonator_id\x18\v \x01(\tR\x0eimpersonatorId\x1a9\n" +
	"\vTraitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"p\n" +
	"\n" +
	"AuthMethod\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12'\n" +
	"\x0faal_contributed\x18\x02 \x01(\tR\x0eaalContributed\x12!\n" +
	"\fcompleted_at\x18\x03 \x01(\x03R\vcompletedAt\"\xa2\x02\n" +
	"\x14CreateSessionRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12\x1f\n" +
	"\vauth_method\x18\x02 \x01(\tR\n" +
	"authMethod\x12\x10\n" +
	"\x03aal\x18\x03 \x01(\tR\x03aal\x127\n" +
	"\x06device\x18\x04 \x01(\v2\x1f.aegion.core.session.DeviceInfoR\x06device\x12)\n" +
	"\x10lifetime_seconds\x18\x05 \x01(\x03R\x0flifetimeSeconds\x12)\n" +
	"\x10is_impersonation\x18\x06 \x01(\bR\x0fisImpersonation\x12'\n" +
	"\x0fimpersonator_id\x18\a \x01(\tR\x0eimpersonatorId\"\x8b\x01\n" +
	"\x15CreateSessionResponse\x12=\n" +
	"\asession\x18\x01 \x01(\v2#.aegion.core.session.SessionContextR\asession\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"csrf_token\x18\x03 \x01(\tR\tcsrfToken\"\xcb\x01\n" +
	"\x14UpdateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\anew_aal\x18\x02 \x01(\tR\x06newAal\x12B\n" +
	"\fadded_method\x18\x03 \x01(\v2\x1f.aegion.core.session.AuthMethodR\vaddedMethod\x127\n" +
	"\x06device\x18\x04 \x01(\v2\x1f.aegion.core.session.DeviceInfoR\x06device\"p\n" +
	"\x15UpdateSessionResponse\x12=\n" +
	"\asession\x18\x01 \x01(\v2#.aegion.core.session.SessionContextR\asession\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"M\n" +
	"\x14RevokeSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"1\n" +
	"\x15RevokeSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"y\n" +
	"\x10RevokeAllRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12,\n" +
	"\x12exclude_session_id\x18\x02 \x01(\tR\x10excludeSessionId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"8\n" +
	"\x11RevokeAllResponse\x12#\n" +
	"\rrevoked_count\x18\x01 \x01(\x05R\frevokedCount\"\x9d\x01\n" +
	"\x13ListSessionsRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12)\n" +
	"\x10include_inactive\x18\x02 \x01(\bR\x0fincludeInactive\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"|\n" +
	"\x14ListSessionsResponse\x12<\n" +
	"\bsessions\x18\x01 \x03(\v2 .aegion.core.session.SessionInfoR\bsessions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xff\x02\n" +
	"\vSessionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03aal\x18\x02 \x01(\tR\x03aal\x12B\n" +
	"\fauth_methods\x18\x03 \x03(\v2\x1f.aegion.core.session.AuthMethodR\vauthMethods\x12\x1b\n" +
	"\tissued_at\x18\x04 \x01(\x03R\bissuedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\x12)\n" +
	"\x10authenticated_at\x18\x06 \x01(\x03R\x0fauthenticatedAt\x12\x16\n" +
	"\x06active\x18\a \x01(\bR\x06active\x127\n" +
	"\x06device\x18\b \x01(\v2\x1f.aegion.core.session.DeviceInfoR\x06device\x12)\n" +
	"\x10is_impersonation\x18\t \x01(\bR\x0fisImpersonation\x12'\n" +
	"\x0fimpersonator_id\x18\n" +
	" \x01(\tR\x0eimpersonatorId\"\xd3\x01\n" +
	"\n" +
	"DeviceInfo\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\x12\x1f\n" +
	"\vdevice_type\x18\x03 \x01(\tR\n" +
	"deviceType\x12\x18\n" +
	"\abrowser\x18\x04 \x01(\tR\abrowser\x12\x0e\n" +
	"\x02os\x18\x05 \x01(\tR\x02os\x12 \n" +
	"\flast_seen_at\x18\x06 \x01(\x03R\n" +
	"lastSeenAt\x12\x1a\n" +
	"\blocation\x18\a \x01(\tR\blocation2\xc2\x04\n" +
	"\x0eSessionService\x12T\n" +
	"\aResolve\x12#.aegion.core.session.ResolveRequest\x1a$.aegion.core.session.ResolveResponse\x12_\n" +
	"\x06Create\x12).aegion.core.session.CreateSessionRequest\x1a*.aegion.core.session.CreateSessionResponse\x12_\n" +
	"\x06Update\x12).aegion.core.session.UpdateSessionRequest\x1a*.aegion.core.session.UpdateSessionResponse\x12_\n" +
	"\x06Revoke\x12).aegion.core.session.RevokeSessionRequest\x1a*.aegion.core.session.RevokeSessionResponse\x12Z\n" +
	"\tRevokeAll\x12%.aegion.core.session.RevokeAllRequest\x1a&.aegion.core.session.RevokeAllResponse\x12[\n" +
	"\x04List\x12(.aegion.core.session.ListSessionsRequest\x1a).aegion.core.session.ListSessionsResponseB.Z,github.com/aegion/aegion/internal/proto/coreb\x06proto3"

var (
	file_core_session_proto_rawDescOnce sync.Once
	file_core_session_proto_rawDescData []byte
)

func file_core_session_proto_rawDescGZIP() []byte {
	file_core_session_proto_rawDescOnce.Do(func() {
		file_core_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_session_proto_rawDesc), len(file_core_session_proto_rawDesc)))
	})
	return file_core_session_proto_rawDescData
}

var file_core_session_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_core_session_proto_goTypes = []any{
	(*ResolveRequest)(nil),        // 0: aegion.core.session.ResolveRequest
	(*ResolveResponse)(nil),       // 1: aegion.core.session.ResolveResponse
	(*SessionContext)(nil),        // 2: aegion.core.session.SessionContext
	(*AuthMethod)(nil),            // 3: aegion.core.session.AuthMethod
	(*CreateSessionRequest)(nil),  // 4: aegion.core.session.CreateSessionRequest
	(*CreateSessionResponse)(nil), // 5: aegion.core.session.CreateSessionResponse
	(*UpdateSessionRequest)(nil),  // 6: aegion.core.session.UpdateSessionRequest
	(*UpdateSessionResponse)(nil), // 7: aegion.core.session.UpdateSessionResponse
	(*RevokeSessionRequest)(nil),  // 8: aegion.core.session.RevokeSessionRequest
	(*RevokeSessionResponse)(nil), // 9: aegion.core.session.RevokeSessionResponse
	(*RevokeAllRequest)(nil),      // 10: aegion.core.session.RevokeAllRequest
	(*RevokeAllResponse)(nil),     // 11: aegion.core.session.RevokeAllResponse
	(*ListSessionsRequest)(nil),   // 12: aegion.core.session.ListSessionsRequest
	(*ListSessionsResponse)(nil),  // 13: aegion.core.session.ListSessionsResponse
	(*SessionInfo)(nil),           // 14: aegion.core.session.SessionInfo
	(*DeviceInfo)(nil),            // 15: aegion.core.session.DeviceInfo
	nil,                           // 16: aegion.core.session.SessionContext.TraitsEntry
	nil,                           // 17: aegion.core.session.SessionContext.MetadataEntry
}
var file_core_session_proto_depIdxs = []int32{
	2,  // 0: aegion.core.session.ResolveResponse.session:type_name -> aegion.core.session.SessionContext
	3,  // 1: aegion.core.session.SessionContext.auth_methods:type_name -> aegion.core.session.AuthMethod
	16, // 2: aegion.core.session.SessionContext.traits:type_name -> aegion.core.session.SessionContext.TraitsEntry
	17, // 3: aegion.core.session.SessionContext.metadata:type_name -> aegion.core.session.SessionContext.MetadataEntry
	15, // 4: aegion.core.session.CreateSessionRequest.device:type_name -> aegion.core.session.DeviceInfo
	2,  // 5: aegion.core.session.CreateSessionResponse.session:type_name -> aegion.core.session.SessionContext
	3,  // 6: aegion.core.session.UpdateSessionRequest.added_method:type_name -> aegion.core.session.AuthMethod
	15, // 7: aegion.core.session.UpdateSessionRequest.device:type_name -> aegion.core.session.DeviceInfo
	2,  // 8: aegion.core.session.UpdateSessionResponse.session:type_name -> aegion.core.session.SessionContext
	14, // 9: aegion.core.session.ListSessionsResponse.sessions:type_name -> aegion.core.session.SessionInfo
	3,  // 10: aegion.core.session.SessionInfo.auth_methods:type_name -> aegion.core.session.AuthMethod
	15, // 11: aegion.core.session.SessionInfo.device:type_name -> aegion.core.session.DeviceInfo
	0,  // 12: aegion.core.session.SessionService.Resolve:input_type -> aegion.core.session.ResolveRequest
	4,  // 13: aegion.core.session.SessionService.Create:input_type -> aegion.core.session.CreateSessionRequest
	6,  // 14: aegion.core.session.SessionService.Update:input_type -> aegion.core.session.UpdateSessionRequest
	8,  // 15: aegion.core.session.SessionService.Revoke:input_type -> aegion.core.session.RevokeSessionRequest
	10, // 16: aegion.core.session.SessionService.RevokeAll:input_type -> aegion.core.session.RevokeAllRequest
	12, // 17: aegion.core.session.SessionService.List:input_type -> aegion.core.session.ListSessionsRequest
	1,  // 18: aegion.core.session.SessionService.Resolve:output_type -> aegion.core.session.ResolveResponse
	5,  // 19: aegion.core.session.SessionService.Create:output_type -> aegion.core.session.CreateSessionResponse
	7,  // 20: aegion.core.session.SessionService.Update:output_type -> aegion.core.session.UpdateSessionResponse
	9,  // 21: aegion.core.session.SessionService.Revoke:output_type -> aegion.core.session.RevokeSessionResponse
	11, // 22: aegion.core.session.SessionService.RevokeAll:output_type -> aegion.core.session.RevokeAllResponse
	13, // 23: aegion.core.session.SessionService.List:output_type -> aegion.core.session.ListSessionsResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_core_session_proto_init() }
func file_core_session_proto_init() {
	if File_core_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_session_proto_rawDesc), len(file_core_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_session_proto_goTypes,
		DependencyIndexes: file_core_session_proto_depIdxs,
		MessageInfos:      file_core_session_proto_msgTypes,
	}.Build()
	File_core_session_proto = out.File
	file_core_session_proto_goTypes = nil
	file_core_session_proto_depIdxs = nil
}
