// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.3
// source: mfa/mfa.proto

package mfapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MFAStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity ID to query.
	IdentityId string `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	// Optional session ID when evaluating step-up requirements.
	SessionId     string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MFAStatusRequest) Reset() {
	*x = MFAStatusRequest{}
	mi := &file_mfa_mfa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MFAStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MFAStatusRequest) ProtoMessage() {}

func (x *MFAStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mfa_mfa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MFAStatusRequest.ProtoReflect.Descriptor instead.
func (*MFAStatusRequest) Descriptor() ([]byte, []int) {
	return file_mfa_mfa_proto_rawDescGZIP(), []int{0}
}

func (x *MFAStatusRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *MFAStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type MFAStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when at least one second-factor method is enrolled.
	MfaEnrolled bool `protobuf:"varint,1,opt,name=mfa_enrolled,json=mfaEnrolled,proto3" json:"mfa_enrolled,omitempty"`
	// Highest achievable AAL from enrolled factors ("aal1" | "aal2").
	HighestAal string `protobuf:"bytes,2,opt,name=highest_aal,json=highestAal,proto3" json:"highest_aal,omitempty"`
	// Enrolled method identifiers ("totp", "webauthn", "sms", ...).
	EnrolledMethods []string `protobuf:"bytes,3,rep,name=enrolled_methods,json=enrolledMethods,proto3" json:"enrolled_methods,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MFAStatusResponse) Reset() {
	*x = MFAStatusResponse{}
	mi := &file_mfa_mfa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MFAStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MFAStatusResponse) ProtoMessage() {}

func (x *MFAStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mfa_mfa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MFAStatusResponse.ProtoReflect.Descriptor instead.
func (*MFAStatusResponse) Descriptor() ([]byte, []int) {
	return file_mfa_mfa_proto_rawDescGZIP(), []int{1}
}

func (x *MFAStatusResponse) GetMfaEnrolled() bool {
	if x != nil {
		return x.MfaEnrolled
	}
	return false
}

func (x *MFAStatusResponse) GetHighestAal() string {
	if x != nil {
		return x.HighestAal
	}
	return ""
}

func (x *MFAStatusResponse) GetEnrolledMethods() []string {
	if x != nil {
		return x.EnrolledMethods
	}
	return nil
}

type FactorListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity ID to query.
	IdentityId    string `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactorListRequest) Reset() {
	*x = FactorListRequest{}
	mi := &file_mfa_mfa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactorListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorListRequest) ProtoMessage() {}

func (x *FactorListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mfa_mfa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorListRequest.ProtoReflect.Descriptor instead.
func (*FactorListRequest) Descriptor() ([]byte, []int) {
	return file_mfa_mfa_proto_rawDescGZIP(), []int{2}
}

func (x *FactorListRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

type FactorListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Factors       []*Factor              `protobuf:"bytes,1,rep,name=factors,proto3" json:"factors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactorListResponse) Reset() {
	*x = FactorListResponse{}
	mi := &file_mfa_mfa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactorListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactorListResponse) ProtoMessage() {}

func (x *FactorListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mfa_mfa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactorListResponse.ProtoReflect.Descriptor instead.
func (*FactorListResponse) Descriptor() ([]byte, []int) {
	return file_mfa_mfa_proto_rawDescGZIP(), []int{3}
}

func (x *FactorListResponse) GetFactors() []*Factor {
	if x != nil {
		return x.Factors
	}
	return nil
}

type Factor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Factor record ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Factor method identifier.
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// Whether the factor was verified during enrollment.
	Verified bool `protobuf:"varint,3,opt,name=verified,proto3" json:"verified,omitempty"`
	// Enrollment timestamp (unix seconds).
	EnrolledAt int64 `protobuf:"varint,4,opt,name=enrolled_at,json=enrolledAt,proto3" json:"enrolled_at,omitempty"`
	// Last use timestamp (unix seconds), 0 if never used.
	LastUsedAt    int64 `protobuf:"varint,5,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Factor) Reset() {
	*x = Factor{}
	mi := &file_mfa_mfa_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Factor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Factor) ProtoMessage() {}

func (x *Factor) ProtoReflect() protoreflect.Message {
	mi := &file_mfa_mfa_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Factor.ProtoReflect.Descriptor instead.
func (*Factor) Descriptor() ([]byte, []int) {
	return file_mfa_mfa_proto_rawDescGZIP(), []int{4}
}

func (x *Factor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Factor) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Factor) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *Factor) GetEnrolledAt() int64 {
	if x != nil {
		return x.EnrolledAt
	}
	return 0
}

func (x *Factor) GetLastUsedAt() int64 {
	if x != nil {
		return x.LastUsedAt
	}
	return 0
}

var File_mfa_mfa_proto protoreflect.FileDescriptor

const file_mfa_mfa_proto_rawDesc = "" +
	"\n" +
	"\rmfa/mfa.proto\x12\raegion.mfa.v1\"R\n" +
	"\x10MFAStatusRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\x82\x01\n" +
	"\x11MFAStatusResponse\x12!\n" +
	"\fmfa_enrolled\x18\x01 \x01(\bR\vmfaEnrolled\x12\x1f\n" +
	"\vhighest_aal\x18\x02 \x01(\tR\n" +
	"highestAal\x12)\n" +
	"\x10enrolled_methods\x18\x03 \x03(\tR\x0fenrolledMethods\"4\n" +
	"\x11FactorListRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\"E\n" +
	"\x12FactorListResponse\x12/\n" +
	"\afactors\x18\x01 \x03(\v2\x15.aegion.mfa.v1.FactorR\afactors\"\x8f\x01\n" +
	"\x06Factor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x1a\n" +
	"\bverified\x18\x03 \x01(\bR\bverified\x12\x1f\n" +
	"\venrolled_at\x18\x04 \x01(\x03R\n" +
	"enrolledAt\x12 \n" +
	"\flast_used_at\x18\x05 \x01(\x03R\n" +
	"lastUsedAt2\xb6\x01\n" +
	"\tMFAEngine\x12N\n" +
	"\tGetStatus\x12\x1f.aegion.mfa.v1.MFAStatusRequest\x1a .aegion.mfa.v1.MFAStatusResponse\x12Y\n" +
	"\x12GetEnrolledFactors\x12 .aegion.mfa.v1.FactorListRequest\x1a!.aegion.mfa.v1.FactorListResponseB6Z4github.com/aegion/aegion/internal/proto/mfa/v1;mfapbb\x06proto3"

var (
	file_mfa_mfa_proto_rawDescOnce sync.Once
	file_mfa_mfa_proto_rawDescData []byte
)

func file_mfa_mfa_proto_rawDescGZIP() []byte {
	file_mfa_mfa_proto_rawDescOnce.Do(func() {
		file_mfa_mfa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mfa_mfa_proto_rawDesc), len(file_mfa_mfa_proto_rawDesc)))
	})
	return file_mfa_mfa_proto_rawDescData
}

var file_mfa_mfa_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_mfa_mfa_proto_goTypes = []any{
	(*MFAStatusRequest)(nil),   // 0: aegion.mfa.v1.MFAStatusRequest
	(*MFAStatusResponse)(nil),  // 1: aegion.mfa.v1.MFAStatusResponse
	(*FactorListRequest)(nil),  // 2: aegion.mfa.v1.FactorListRequest
	(*FactorListResponse)(nil), // 3: aegion.mfa.v1.FactorListResponse
	(*Factor)(nil),             // 4: aegion.mfa.v1.Factor
}
var file_mfa_mfa_proto_depIdxs = []int32{
	4, // 0: aegion.mfa.v1.FactorListResponse.factors:type_name -> aegion.mfa.v1.Factor
	0, // 1: aegion.mfa.v1.MFAEngine.GetStatus:input_type -> aegion.mfa.v1.MFAStatusRequest
	2, // 2: aegion.mfa.v1.MFAEngine.GetEnrolledFactors:input_type -> aegion.mfa.v1.FactorListRequest
	1, // 3: aegion.mfa.v1.MFAEngine.GetStatus:output_type -> aegion.mfa.v1.MFAStatusResponse
	3, // 4: aegion.mfa.v1.MFAEngine.GetEnrolledFactors:output_type -> aegion.mfa.v1.FactorListResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mfa_mfa_proto_init() }
func file_mfa_mfa_proto_init() {
	if File_mfa_mfa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mfa_mfa_proto_rawDesc), len(file_mfa_mfa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mfa_mfa_proto_goTypes,
		DependencyIndexes: file_mfa_mfa_proto_depIdxs,
		MessageInfos:      file_mfa_mfa_proto_msgTypes,
	}.Build()
	File_mfa_mfa_proto = out.File
	file_mfa_mfa_proto_goTypes = nil
	file_mfa_mfa_proto_depIdxs = nil
}
