// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: mfa/mfa.proto

package mfapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MFAEngine_GetStatus_FullMethodName          = "/aegion.mfa.v1.MFAEngine/GetStatus"
	MFAEngine_GetEnrolledFactors_FullMethodName = "/aegion.mfa.v1.MFAEngine/GetEnrolledFactors"
)

// MFAEngineClient is the client API for MFAEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MFAEngine provides cross-module MFA status and enrollment reads.
type MFAEngineClient interface {
	// GetStatus returns aggregate MFA status for an identity.
	GetStatus(ctx context.Context, in *MFAStatusRequest, opts ...grpc.CallOption) (*MFAStatusResponse, error)
	// GetEnrolledFactors returns enrolled factors for an identity.
	GetEnrolledFactors(ctx context.Context, in *FactorListRequest, opts ...grpc.CallOption) (*FactorListResponse, error)
}

type mFAEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewMFAEngineClient(cc grpc.ClientConnInterface) MFAEngineClient {
	return &mFAEngineClient{cc}
}

func (c *mFAEngineClient) GetStatus(ctx context.Context, in *MFAStatusRequest, opts ...grpc.CallOption) (*MFAStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MFAStatusResponse)
	err := c.cc.Invoke(ctx, MFAEngine_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mFAEngineClient) GetEnrolledFactors(ctx context.Context, in *FactorListRequest, opts ...grpc.CallOption) (*FactorListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FactorListResponse)
	err := c.cc.Invoke(ctx, MFAEngine_GetEnrolledFactors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MFAEngineServer is the server API for MFAEngine service.
// All implementations must embed UnimplementedMFAEngineServer
// for forward compatibility.
//
// MFAEngine provides cross-module MFA status and enrollment reads.
type MFAEngineServer interface {
	// GetStatus returns aggregate MFA status for an identity.
	GetStatus(context.Context, *MFAStatusRequest) (*MFAStatusResponse, error)
	// GetEnrolledFactors returns enrolled factors for an identity.
	GetEnrolledFactors(context.Context, *FactorListRequest) (*FactorListResponse, error)
	mustEmbedUnimplementedMFAEngineServer()
}

// UnimplementedMFAEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMFAEngineServer struct{}

func (UnimplementedMFAEngineServer) GetStatus(context.Context, *MFAStatusRequest) (*MFAStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedMFAEngineServer) GetEnrolledFactors(context.Context, *FactorListRequest) (*FactorListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnrolledFactors not implemented")
}
func (UnimplementedMFAEngineServer) mustEmbedUnimplementedMFAEngineServer() {}
func (UnimplementedMFAEngineServer) testEmbeddedByValue()                   {}

// UnsafeMFAEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MFAEngineServer will
// result in compilation errors.
type UnsafeMFAEngineServer interface {
	mustEmbedUnimplementedMFAEngineServer()
}

func RegisterMFAEngineServer(s grpc.ServiceRegistrar, srv MFAEngineServer) {
	// If the following call pancis, it indicates UnimplementedMFAEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MFAEngine_ServiceDesc, srv)
}

func _MFAEngine_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MFAStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MFAEngineServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MFAEngine_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MFAEngineServer).GetStatus(ctx, req.(*MFAStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MFAEngine_GetEnrolledFactors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FactorListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MFAEngineServer).GetEnrolledFactors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MFAEngine_GetEnrolledFactors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MFAEngineServer).GetEnrolledFactors(ctx, req.(*FactorListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MFAEngine_ServiceDesc is the grpc.ServiceDesc for MFAEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MFAEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aegion.mfa.v1.MFAEngine",
	HandlerType: (*MFAEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _MFAEngine_GetStatus_Handler,
		},
		{
			MethodName: "GetEnrolledFactors",
			Handler:    _MFAEngine_GetEnrolledFactors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mfa/mfa.proto",
}
