#!/bin/bash
# Generate CGo bindings for Rust libraries
set -e

RUST_DIR="rust"

echo "Building Rust libraries..."
cd "$RUST_DIR"
cargo build --release

echo "Generating CGo headers..."
# Headers are generated by cbindgen via Cargo build scripts

echo "CGo binding generation complete!"
echo "Headers available at:"
echo "  - rust/crypto/target/crypto.h"
echo "  - rust/jwt/target/jwt.h"
