// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: oauth2/tokens.proto

package oauth2pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TokenStore_Introspect_FullMethodName       = "/aegion.oauth2.v1.TokenStore/Introspect"
	TokenStore_Revoke_FullMethodName           = "/aegion.oauth2.v1.TokenStore/Revoke"
	TokenStore_InvalidateFamily_FullMethodName = "/aegion.oauth2.v1.TokenStore/InvalidateFamily"
)

// TokenStoreClient is the client API for TokenStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TokenStore exposes token lifecycle operations for other modules.
type TokenStoreClient interface {
	// Introspect checks whether a token is active and returns token metadata.
	Introspect(ctx context.Context, in *IntrospectRequest, opts ...grpc.CallOption) (*IntrospectResponse, error)
	// Revoke revokes a token by identifier.
	Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error)
	// InvalidateFamily revokes all refresh tokens in a family.
	InvalidateFamily(ctx context.Context, in *InvalidateFamilyRequest, opts ...grpc.CallOption) (*InvalidateFamilyResponse, error)
}

type tokenStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenStoreClient(cc grpc.ClientConnInterface) TokenStoreClient {
	return &tokenStoreClient{cc}
}

func (c *tokenStoreClient) Introspect(ctx context.Context, in *IntrospectRequest, opts ...grpc.CallOption) (*IntrospectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntrospectResponse)
	err := c.cc.Invoke(ctx, TokenStore_Introspect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenStoreClient) Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeResponse)
	err := c.cc.Invoke(ctx, TokenStore_Revoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenStoreClient) InvalidateFamily(ctx context.Context, in *InvalidateFamilyRequest, opts ...grpc.CallOption) (*InvalidateFamilyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvalidateFamilyResponse)
	err := c.cc.Invoke(ctx, TokenStore_InvalidateFamily_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenStoreServer is the server API for TokenStore service.
// All implementations must embed UnimplementedTokenStoreServer
// for forward compatibility.
//
// TokenStore exposes token lifecycle operations for other modules.
type TokenStoreServer interface {
	// Introspect checks whether a token is active and returns token metadata.
	Introspect(context.Context, *IntrospectRequest) (*IntrospectResponse, error)
	// Revoke revokes a token by identifier.
	Revoke(context.Context, *RevokeRequest) (*RevokeResponse, error)
	// InvalidateFamily revokes all refresh tokens in a family.
	InvalidateFamily(context.Context, *InvalidateFamilyRequest) (*InvalidateFamilyResponse, error)
	mustEmbedUnimplementedTokenStoreServer()
}

// UnimplementedTokenStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenStoreServer struct{}

func (UnimplementedTokenStoreServer) Introspect(context.Context, *IntrospectRequest) (*IntrospectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Introspect not implemented")
}
func (UnimplementedTokenStoreServer) Revoke(context.Context, *RevokeRequest) (*RevokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Revoke not implemented")
}
func (UnimplementedTokenStoreServer) InvalidateFamily(context.Context, *InvalidateFamilyRequest) (*InvalidateFamilyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvalidateFamily not implemented")
}
func (UnimplementedTokenStoreServer) mustEmbedUnimplementedTokenStoreServer() {}
func (UnimplementedTokenStoreServer) testEmbeddedByValue()                    {}

// UnsafeTokenStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenStoreServer will
// result in compilation errors.
type UnsafeTokenStoreServer interface {
	mustEmbedUnimplementedTokenStoreServer()
}

func RegisterTokenStoreServer(s grpc.ServiceRegistrar, srv TokenStoreServer) {
	// If the following call pancis, it indicates UnimplementedTokenStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TokenStore_ServiceDesc, srv)
}

func _TokenStore_Introspect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntrospectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenStoreServer).Introspect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenStore_Introspect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenStoreServer).Introspect(ctx, req.(*IntrospectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenStore_Revoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenStoreServer).Revoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenStore_Revoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenStoreServer).Revoke(ctx, req.(*RevokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenStore_InvalidateFamily_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvalidateFamilyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenStoreServer).InvalidateFamily(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenStore_InvalidateFamily_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenStoreServer).InvalidateFamily(ctx, req.(*InvalidateFamilyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenStore_ServiceDesc is the grpc.ServiceDesc for TokenStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aegion.oauth2.v1.TokenStore",
	HandlerType: (*TokenStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Introspect",
			Handler:    _TokenStore_Introspect_Handler,
		},
		{
			MethodName: "Revoke",
			Handler:    _TokenStore_Revoke_Handler,
		},
		{
			MethodName: "InvalidateFamily",
			Handler:    _TokenStore_InvalidateFamily_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oauth2/tokens.proto",
}
