// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: oauth2/tokens.proto

package oauth2pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntrospectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token identifier or opaque token string.
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntrospectRequest) Reset() {
	*x = IntrospectRequest{}
	mi := &file_oauth2_tokens_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectRequest) ProtoMessage() {}

func (x *IntrospectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_tokens_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectRequest.ProtoReflect.Descriptor instead.
func (*IntrospectRequest) Descriptor() ([]byte, []int) {
	return file_oauth2_tokens_proto_rawDescGZIP(), []int{0}
}

func (x *IntrospectRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type IntrospectResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Active     bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	ClientId   string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	IdentityId string                 `protobuf:"bytes,3,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	Scopes     []string               `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	Audience   []string               `protobuf:"bytes,5,rep,name=audience,proto3" json:"audience,omitempty"`
	// Expiry timestamp (unix seconds), 0 when inactive/unknown.
	ExpiresAt     int64 `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntrospectResponse) Reset() {
	*x = IntrospectResponse{}
	mi := &file_oauth2_tokens_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectResponse) ProtoMessage() {}

func (x *IntrospectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_tokens_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectResponse.ProtoReflect.Descriptor instead.
func (*IntrospectResponse) Descriptor() ([]byte, []int) {
	return file_oauth2_tokens_proto_rawDescGZIP(), []int{1}
}

func (x *IntrospectResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *IntrospectResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *IntrospectResponse) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *IntrospectResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *IntrospectResponse) GetAudience() []string {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *IntrospectResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type RevokeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token identifier or opaque token string.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// Optional operator/system reason for audit trails.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_oauth2_tokens_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_tokens_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_oauth2_tokens_proto_rawDescGZIP(), []int{2}
}

func (x *RevokeRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RevokeRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RevokeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True when the token existed and was revoked.
	Revoked       bool `protobuf:"varint,1,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeResponse) Reset() {
	*x = RevokeResponse{}
	mi := &file_oauth2_tokens_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeResponse) ProtoMessage() {}

func (x *RevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_tokens_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeResponse.ProtoReflect.Descriptor instead.
func (*RevokeResponse) Descriptor() ([]byte, []int) {
	return file_oauth2_tokens_proto_rawDescGZIP(), []int{3}
}

func (x *RevokeResponse) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

type InvalidateFamilyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Refresh token family identifier.
	FamilyId      string `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateFamilyRequest) Reset() {
	*x = InvalidateFamilyRequest{}
	mi := &file_oauth2_tokens_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateFamilyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateFamilyRequest) ProtoMessage() {}

func (x *InvalidateFamilyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_tokens_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateFamilyRequest.ProtoReflect.Descriptor instead.
func (*InvalidateFamilyRequest) Descriptor() ([]byte, []int) {
	return file_oauth2_tokens_proto_rawDescGZIP(), []int{4}
}

func (x *InvalidateFamilyRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

type InvalidateFamilyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of refresh tokens invalidated.
	Invalidated   int64 `protobuf:"varint,1,opt,name=invalidated,proto3" json:"invalidated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateFamilyResponse) Reset() {
	*x = InvalidateFamilyResponse{}
	mi := &file_oauth2_tokens_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateFamilyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateFamilyResponse) ProtoMessage() {}

func (x *InvalidateFamilyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oauth2_tokens_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateFamilyResponse.ProtoReflect.Descriptor instead.
func (*InvalidateFamilyResponse) Descriptor() ([]byte, []int) {
	return file_oauth2_tokens_proto_rawDescGZIP(), []int{5}
}

func (x *InvalidateFamilyResponse) GetInvalidated() int64 {
	if x != nil {
		return x.Invalidated
	}
	return 0
}

var File_oauth2_tokens_proto protoreflect.FileDescriptor

const file_oauth2_tokens_proto_rawDesc = "" +
	"\n" +
	"\x13oauth2/tokens.proto\x12\x10aegion.oauth2.v1\")\n" +
	"\x11IntrospectRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xbd\x01\n" +
	"\x12IntrospectResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x1f\n" +
	"\videntity_id\x18\x03 \x01(\tR\n" +
	"identityId\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\x12\x1a\n" +
	"\baudience\x18\x05 \x03(\tR\baudience\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\"=\n" +
	"\rRevokeRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"*\n" +
	"\x0eRevokeResponse\x12\x18\n" +
	"\arevoked\x18\x01 \x01(\bR\arevoked\"6\n" +
	"\x17InvalidateFamilyRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\"<\n" +
	"\x18InvalidateFamilyResponse\x12 \n" +
	"\vinvalidated\x18\x01 \x01(\x03R\vinvalidated2\x9d\x02\n" +
	"\n" +
	"TokenStore\x12W\n" +
	"\n" +
	"Introspect\x12#.aegion.oauth2.v1.IntrospectRequest\x1a$.aegion.oauth2.v1.IntrospectResponse\x12K\n" +
	"\x06Revoke\x12\x1f.aegion.oauth2.v1.RevokeRequest\x1a .aegion.oauth2.v1.RevokeResponse\x12i\n" +
	"\x10InvalidateFamily\x12).aegion.oauth2.v1.InvalidateFamilyRequest\x1a*.aegion.oauth2.v1.InvalidateFamilyResponseB<Z:github.com/aegion/aegion/internal/proto/oauth2/v1;oauth2pbb\x06proto3"

var (
	file_oauth2_tokens_proto_rawDescOnce sync.Once
	file_oauth2_tokens_proto_rawDescData []byte
)

func file_oauth2_tokens_proto_rawDescGZIP() []byte {
	file_oauth2_tokens_proto_rawDescOnce.Do(func() {
		file_oauth2_tokens_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oauth2_tokens_proto_rawDesc), len(file_oauth2_tokens_proto_rawDesc)))
	})
	return file_oauth2_tokens_proto_rawDescData
}

var file_oauth2_tokens_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_oauth2_tokens_proto_goTypes = []any{
	(*IntrospectRequest)(nil),        // 0: aegion.oauth2.v1.IntrospectRequest
	(*IntrospectResponse)(nil),       // 1: aegion.oauth2.v1.IntrospectResponse
	(*RevokeRequest)(nil),            // 2: aegion.oauth2.v1.RevokeRequest
	(*RevokeResponse)(nil),           // 3: aegion.oauth2.v1.RevokeResponse
	(*InvalidateFamilyRequest)(nil),  // 4: aegion.oauth2.v1.InvalidateFamilyRequest
	(*InvalidateFamilyResponse)(nil), // 5: aegion.oauth2.v1.InvalidateFamilyResponse
}
var file_oauth2_tokens_proto_depIdxs = []int32{
	0, // 0: aegion.oauth2.v1.TokenStore.Introspect:input_type -> aegion.oauth2.v1.IntrospectRequest
	2, // 1: aegion.oauth2.v1.TokenStore.Revoke:input_type -> aegion.oauth2.v1.RevokeRequest
	4, // 2: aegion.oauth2.v1.TokenStore.InvalidateFamily:input_type -> aegion.oauth2.v1.InvalidateFamilyRequest
	1, // 3: aegion.oauth2.v1.TokenStore.Introspect:output_type -> aegion.oauth2.v1.IntrospectResponse
	3, // 4: aegion.oauth2.v1.TokenStore.Revoke:output_type -> aegion.oauth2.v1.RevokeResponse
	5, // 5: aegion.oauth2.v1.TokenStore.InvalidateFamily:output_type -> aegion.oauth2.v1.InvalidateFamilyResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_oauth2_tokens_proto_init() }
func file_oauth2_tokens_proto_init() {
	if File_oauth2_tokens_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oauth2_tokens_proto_rawDesc), len(file_oauth2_tokens_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oauth2_tokens_proto_goTypes,
		DependencyIndexes: file_oauth2_tokens_proto_depIdxs,
		MessageInfos:      file_oauth2_tokens_proto_msgTypes,
	}.Build()
	File_oauth2_tokens_proto = out.File
	file_oauth2_tokens_proto_goTypes = nil
	file_oauth2_tokens_proto_depIdxs = nil
}
